// 타투 세부 모티브 사전 — '도안' 그룹(21개 큰 묶음) 아래에서 실제로 무엇을 그렸는지 (장미 · 늑대 · 나침반 …)
//
// 속성 사전(taxonomy.js)과 따로 두어, 모티브를 늘리거나 고쳐도 학습 헤드(해시)가 꺼지지 않는다.
// 판단: 모티브 문장 임베딩(embeddings/motifs-*.json) 제로샷 × 부모 '도안' 확률 + 라벨 단 학습 사진 kNN (motif.js)
//   ko: 화면에 쓰는 이름 · parent: taxonomy.js tattoo.subject 라벨 · en: 영어 묘사(여러 개면 평균) · hint: 한 줄 설명
export const MOTIF_TEMPLATES = ['a photo of a tattoo of {}', 'a tattoo design of {}', 'a {} tattoo on skin'];

export const MOTIFS = [
  // 꽃 · 식물
  { ko: '장미', parent: '꽃·식물', en: ['a rose', 'a rose flower with thorny stem'] },
  { ko: '모란', parent: '꽃·식물', en: ['a peony flower'] },
  { ko: '벚꽃', parent: '꽃·식물', en: ['cherry blossoms', 'sakura flowers on a branch'] },
  { ko: '연꽃', parent: '꽃·식물', en: ['a lotus flower'] },
  { ko: '해바라기', parent: '꽃·식물', en: ['a sunflower'] },
  { ko: '튤립', parent: '꽃·식물', en: ['a tulip'] },
  { ko: '라벤더', parent: '꽃·식물', en: ['lavender sprigs'] },
  { ko: '데이지', parent: '꽃·식물', en: ['a daisy flower'] },
  { ko: '국화', parent: '꽃·식물', en: ['a chrysanthemum flower'] },
  { ko: '야생화 · 꽃다발', parent: '꽃·식물', en: ['a bouquet of wildflowers', 'small wildflowers'] },
  { ko: '잎사귀 · 넝쿨', parent: '꽃·식물', en: ['leaves on a vine', 'a leafy branch', 'fern leaves'] },
  { ko: '나무', parent: '꽃·식물', en: ['a tree with branches and roots', 'a pine tree'] },
  { ko: '선인장', parent: '꽃·식물', en: ['a cactus'] },
  { ko: '버섯', parent: '꽃·식물', en: ['a mushroom'] },
  { ko: '백합', parent: '꽃·식물', en: ['a lily flower', 'a tiger lily'] },
  { ko: '히비스커스', parent: '꽃·식물', en: ['a hibiscus flower'] },
  { ko: '클로버', parent: '꽃·식물', en: ['a shamrock', 'a four-leaf clover'] },
  { ko: '과일', parent: '꽃·식물', en: ['fruit such as cherries, a lemon or a strawberry'] },
  // 동물 (야생)
  { ko: '늑대', parent: '동물', en: ['a wolf', 'a howling wolf head'] },
  { ko: '사자', parent: '동물', en: ['a lion head with a mane'] },
  { ko: '여우', parent: '동물', en: ['a fox'] },
  { ko: '사슴', parent: '동물', en: ['a deer with antlers', 'a stag'] },
  { ko: '곰', parent: '동물', en: ['a bear'] },
  { ko: '코끼리', parent: '동물', en: ['an elephant'] },
  { ko: '말', parent: '동물', en: ['a horse'] },
  { ko: '토끼', parent: '동물', en: ['a rabbit'] },
  { ko: '표범 · 재규어', parent: '동물', en: ['a panther', 'a leopard or jaguar'] },
  { ko: '고래', parent: '동물', en: ['a whale'] },
  { ko: '상어', parent: '동물', en: ['a shark'] },
  { ko: '문어 · 오징어', parent: '동물', en: ['an octopus with tentacles'] },
  { ko: '해파리', parent: '동물', en: ['a jellyfish'] },
  { ko: '거북', parent: '동물', en: ['a sea turtle'] },
  { ko: '물고기', parent: '동물', en: ['a fish'] },
  { ko: '거미', parent: '동물', en: ['a spider', 'a spider web'] },
  { ko: '전갈', parent: '동물', en: ['a scorpion'] },
  { ko: '벌 · 곤충', parent: '동물', en: ['a bee', 'a beetle or insect', 'a dragonfly'] },
  { ko: '박쥐', parent: '동물', en: ['a bat with spread wings'] },
  { ko: '도마뱀 · 카멜레온', parent: '동물', en: ['a lizard', 'a chameleon', 'a gecko'] },
  { ko: '판다', parent: '동물', en: ['a panda'] },
  { ko: '개구리', parent: '동물', en: ['a frog'] },
  { ko: '공룡', parent: '동물', en: ['a dinosaur'] },
  // 반려동물
  { ko: '강아지', parent: '반려동물', en: ['a pet dog portrait', 'a puppy'] },
  { ko: '고양이', parent: '반려동물', en: ['a cat', 'a pet cat portrait'] },
  { ko: '발자국', parent: '반려동물', en: ['paw prints'] },
  // 뱀
  { ko: '뱀', parent: '뱀', en: ['a coiled snake', 'a serpent'] },
  { ko: '뱀과 꽃', parent: '뱀', en: ['a snake wrapped around a flower'] },
  { ko: '뱀과 단검', parent: '뱀', en: ['a snake wrapped around a dagger'] },
  // 나비 · 새
  { ko: '나비', parent: '나비·새', en: ['a butterfly'] },
  { ko: '나방', parent: '나비·새', en: ['a moth with a skull pattern', 'a moth'] },
  { ko: '제비 · 작은 새', parent: '나비·새', en: ['a swallow bird', 'small flying birds'] },
  { ko: '독수리 · 매', parent: '나비·새', en: ['an eagle with spread wings', 'a hawk'] },
  { ko: '부엉이', parent: '나비·새', en: ['an owl'] },
  { ko: '까마귀', parent: '나비·새', en: ['a crow or raven'] },
  { ko: '벌새', parent: '나비·새', en: ['a hummingbird'] },
  { ko: '공작', parent: '나비·새', en: ['a peacock with its feathers'] },
  { ko: '닭', parent: '나비·새', en: ['a rooster'] },
  { ko: '앵무새', parent: '나비·새', en: ['a parrot'] },
  { ko: '깃털', parent: '나비·새', en: ['a feather'] },
  { ko: '날개', parent: '나비·새', en: ['a pair of wings'] },
  // 문구 · 이니셜
  { ko: '영문 레터링', parent: '문구·이니셜', en: ['a word or quote in cursive script', 'english lettering text'] },
  { ko: '한글 레터링', parent: '문구·이니셜', en: ['korean hangul letters'] },
  { ko: '한자 · 일본어', parent: '문구·이니셜', en: ['chinese or japanese characters'] },
  { ko: '이니셜', parent: '문구·이니셜', en: ['a single initial letter', 'initials'] },
  { ko: '날짜 · 숫자', parent: '문구·이니셜', en: ['a date or numbers', 'roman numerals'] },
  { ko: '좌표 · 서명', parent: '문구·이니셜', en: ['coordinates', 'a handwritten signature'] },
  // 만다라 · 기하학
  { ko: '만다라', parent: '만다라·기하학', en: ['a mandala'] },
  { ko: '기하학 도형', parent: '만다라·기하학', en: ['geometric shapes, triangles and lines', 'sacred geometry'] },
  { ko: '패턴 · 문양', parent: '만다라·기하학', en: ['an ornamental pattern', 'a henna-like lace pattern'] },
  { ko: '밴드 · 띠', parent: '만다라·기하학', en: ['an armband', 'a band wrapped around the arm'] },
  // 인물
  { ko: '여성 초상', parent: '인물', en: ['a portrait of a woman'] },
  { ko: '남성 초상', parent: '인물', en: ['a portrait of a man'] },
  { ko: '아기 · 아이', parent: '인물', en: ['a baby or child portrait'] },
  { ko: '조각상', parent: '인물', en: ['a greek statue head', 'a classical sculpture'] },
  { ko: '눈', parent: '인물', en: ['a single eye', 'an all-seeing eye'] },
  { ko: '손', parent: '인물', en: ['hands', 'a hand gesture'] },
  { ko: '입술', parent: '인물', en: ['lips', 'a kiss mark'] },
  { ko: '해골 가면 여인', parent: '인물', en: ['a woman with sugar skull face paint', 'la catrina'] },
  { ko: '초현실 얼굴', parent: '인물', en: ['a surreal distorted face', 'a surreal face with tears or bones'] },
  { ko: '전사 · 기사', parent: '인물', en: ['a warrior helmet', 'a samurai', 'a knight'] },
  // 달 · 별 · 자연
  { ko: '달', parent: '달·별·자연', en: ['a crescent moon', 'moon phases'] },
  { ko: '해', parent: '달·별·자연', en: ['a sun with rays'] },
  { ko: '별', parent: '달·별·자연', en: ['stars', 'a nautical star'] },
  { ko: '별자리 · 우주', parent: '달·별·자연', en: ['a constellation', 'planets and outer space'] },
  { ko: '산', parent: '달·별·자연', en: ['mountains'] },
  { ko: '구름 · 번개', parent: '달·별·자연', en: ['clouds', 'a lightning bolt'] },
  { ko: '불꽃', parent: '달·별·자연', en: ['flames'] },
  // 동양 전통
  { ko: '용', parent: '용·호랑이·잉어', en: ['an asian dragon'] },
  { ko: '호랑이', parent: '용·호랑이·잉어', en: ['a tiger'] },
  { ko: '잉어', parent: '용·호랑이·잉어', en: ['a koi fish'] },
  { ko: '봉황 · 불사조', parent: '용·호랑이·잉어', en: ['a phoenix'] },
  { ko: '한냐 가면', parent: '용·호랑이·잉어', en: ['a hannya mask', 'an oni demon mask'] },
  { ko: '사무라이 · 무사', parent: '용·호랑이·잉어', en: ['a japanese samurai warrior'] },
  { ko: '해태 · 사자개', parent: '용·호랑이·잉어', en: ['a chinese foo dog guardian lion', 'a japanese komainu lion dog'] },
  { ko: '학', parent: '용·호랑이·잉어', en: ['a crane bird'] },
  { ko: '풍신 · 뇌신', parent: '용·호랑이·잉어', en: ['japanese wind and thunder gods'] },
  // 해골 · 다크
  { ko: '해골', parent: '해골·다크', en: ['a human skull'] },
  { ko: '슈가 스컬', parent: '해골·다크', en: ['a decorated mexican sugar skull'] },
  { ko: '해골과 장미', parent: '해골·다크', en: ['a skull with roses'] },
  { ko: '사신', parent: '해골·다크', en: ['the grim reaper with a scythe'] },
  { ko: '악마', parent: '해골·다크', en: ['a demon or devil with horns'] },
  { ko: '뼈 · 해골 손', parent: '해골·다크', en: ['skeleton bones', 'a skeleton hand'] },
  // 천사 · 종교
  { ko: '십자가', parent: '천사·종교', en: ['a cross', 'a crucifix'] },
  { ko: '묵주', parent: '천사·종교', en: ['a rosary'] },
  { ko: '기도하는 손', parent: '천사·종교', en: ['praying hands'] },
  { ko: '천사', parent: '천사·종교', en: ['an angel', 'a cherub'] },
  { ko: '성모 · 예수', parent: '천사·종교', en: ['the virgin mary', 'jesus christ'] },
  { ko: '힌두 신', parent: '천사·종교', en: ['the hindu god ganesha', 'a hindu deity'] },
  { ko: '부처 · 불교', parent: '천사·종교', en: ['buddha', 'a buddhist symbol'] },
  { ko: '성심', parent: '천사·종교', en: ['a sacred heart with flames'] },
  // 캐릭터
  { ko: '애니 캐릭터', parent: '캐릭터', en: ['an anime character'] },
  { ko: '만화 캐릭터', parent: '캐릭터', en: ['a cartoon character', 'a disney character'] },
  { ko: '게임 · 영화 캐릭터', parent: '캐릭터', en: ['a video game character', 'a movie character'] },
  // 리본 · 체인
  { ko: '리본', parent: '리본·체인', en: ['a ribbon bow'] },
  { ko: '체인', parent: '리본·체인', en: ['a chain'] },
  { ko: '목걸이 · 팔찌', parent: '리본·체인', en: ['a necklace or bracelet design'] },
  // 하트 · 심볼
  { ko: '하트', parent: '하트·심볼', en: ['a heart'] },
  { ko: '무한대', parent: '하트·심볼', en: ['an infinity symbol'] },
  { ko: '화살', parent: '하트·심볼', en: ['an arrow'] },
  { ko: '심전도', parent: '하트·심볼', en: ['a heartbeat line'] },
  { ko: '왕관', parent: '하트·심볼', en: ['a crown'] },
  { ko: '트럼프 카드 · 주사위', parent: '하트·심볼', en: ['playing cards', 'dice'] },
  { ko: '국기 · 지도', parent: '하트·심볼', en: ['a national flag', 'a map outline of a country or state'] },
  { ko: '로고 · 엠블럼', parent: '하트·심볼', en: ['a logo or emblem', 'a barcode'] },
  { ko: '스마일 · 이모지', parent: '하트·심볼', en: ['a smiley face'] },
  { ko: '평화 · 음양', parent: '하트·심볼', en: ['a peace sign', 'a yin yang symbol'] },
  // 사물
  { ko: '닻', parent: '사물', en: ['an anchor'] },
  { ko: '나침반', parent: '사물', en: ['a compass'] },
  { ko: '배', parent: '사물', en: ['a sailing ship'] },
  { ko: '등대', parent: '사물', en: ['a lighthouse'] },
  { ko: '모래시계', parent: '사물', en: ['an hourglass'] },
  { ko: '카메라', parent: '사물', en: ['a camera'] },
  { ko: '비행기 · 탈것', parent: '사물', en: ['an airplane', 'a car or motorcycle'] },
  { ko: '보석 · 다이아몬드', parent: '사물', en: ['a diamond gem'] },
  { ko: '촛불 · 램프', parent: '사물', en: ['a candle', 'a lantern'] },
  { ko: '열기구 · 풍선', parent: '사물', en: ['a hot air balloon', 'a balloon'] },
  { ko: '총', parent: '사물', en: ['a gun or revolver'] },
  { ko: '곰인형', parent: '사물', en: ['a teddy bear', 'a stitched teddy bear'] },
  { ko: '지구본', parent: '사물', en: ['a globe with a banner', 'a world globe'] },
  { ko: '전구', parent: '사물', en: ['a light bulb'] },
  { ko: '음식 · 음료', parent: '사물', en: ['food or a drink', 'a coffee cup'] },
  // 파도 · 바다
  { ko: '파도', parent: '파도·바다', en: ['a great wave', 'ocean waves'] },
  { ko: '조개 · 바다 생물', parent: '파도·바다', en: ['a seashell', 'coral'] },
  { ko: '인어', parent: '파도·바다', en: ['a mermaid'] },
  // 칼 · 무기
  { ko: '단검', parent: '칼·무기', en: ['a dagger'] },
  { ko: '검 · 카타나', parent: '칼·무기', en: ['a sword', 'a katana'] },
  { ko: '도끼 · 창', parent: '칼·무기', en: ['an axe', 'a spear'] },
  // 시계 · 열쇠
  { ko: '시계', parent: '시계·열쇠', en: ['a pocket watch', 'a clock face'] },
  { ko: '열쇠', parent: '시계·열쇠', en: ['a key'] },
  { ko: '자물쇠', parent: '시계·열쇠', en: ['a padlock'] },
  // 음악 · 악기
  { ko: '음표', parent: '음악·악기', en: ['musical notes'] },
  { ko: '기타', parent: '음악·악기', en: ['a guitar'] },
  { ko: '피아노 · 악기', parent: '음악·악기', en: ['piano keys', 'a musical instrument'] },
  { ko: '헤드폰 · 마이크', parent: '음악·악기', en: ['headphones', 'a microphone'] },
  // 풍경 · 건물
  { ko: '숲 · 산 풍경', parent: '풍경·건물', en: ['a forest landscape', 'a mountain landscape scene'] },
  { ko: '도시 · 건물', parent: '풍경·건물', en: ['a city skyline', 'a building'] },
  { ko: '성 · 탑', parent: '풍경·건물', en: ['a castle', 'a tower'] },
];
