// 속성 사전 (Taxonomy) — 한국 인스타그램 · 네이버 뷰티 용어 기준
//
// - 각 카테고리는 여러 "속성 그룹"으로 구성되고, 그룹마다 독립적으로 분류한다.
// - ko   : 화면에 보이는 이름 (한국 SNS 에서 실제로 쓰는 표현)
// - en   : 모델(CLIP)에 넣는 영어 설명 — 구체적일수록 정확도가 오른다
// - tag  : 해시태그 (없으면 ko + 그룹의 tagSuffix 로 만든다)
// - tone : 'cool' | 'warm' | 'neutral' — 컬러 라벨이 가진 톤 (톤 판정에 사전 정보로 쓴다)
// - templates : 라벨(en)을 감싸는 문장 틀. 여러 개를 평균내면(prompt ensembling) 안정적이다.
// - hidden    : 화면 후보·태그에 노출하지 않는 보조 라벨
// - def       : 한 줄 용어 설명 (결과 화면의 장르 · 속성 아래에 보여 준다)
// - syn       : 같은 스타일을 부르는 다른 이름 · 검색어 (화면에 '같은 말'로 보여 주고 검색에 쓴다). 근거는 docs/LABEL_RESEARCH.md

export const CATEGORY_ORDER = ['hair', 'nail', 'makeup', 'tattoo'];

// 뷰티 사진이 아닌 경우를 가려내기 위한 문장 (이쪽이 이기면 "뷰티 사진이 아닐 수 있어요" 안내)
export const OTHER_DETECT = [
  'a photo of a landscape, a street or a building',
  'a photo of food or a drink',
  'a photo of a pet or a wild animal',
  'a product photo of a cosmetic bottle, a tube or a package on a table',
  'a cartoon, a drawing, a painting or an illustration',
  'a photo of hardware, tools, screws or metal nails',
  'a screenshot or a document with text',
  'a photo of a car, furniture or an everyday object',
];

export const TAXONOMY = {
  // ───────────────────────────────────────────────────────────── 헤어
  hair: {
    label: '헤어',
    icon: '💇',
    detect: [
      'a photo of a person showing their hairstyle',
      "a photo of someone's haircut and hair color",
      'a hair salon photo where the hair is the main subject',
    ],
    groups: [
      {
        key: 'length', label: '기장',
        templates: ['a photo of a person with {}', 'a hairstyle photo showing {}'],
        labels: [
          { ko: '숏컷', en: 'very short cropped hair above the ears', syn: ['짧은머리', '남자 짧은머리'], def: '귀가 드러날 만큼 짧게 자른, 가장 짧은 머리 기장이에요.' },
          { ko: '단발', en: 'chin-length bob hair that ends around the jawline', syn: ['턱선 단발', '보브 기장'], def: '머리끝이 턱선 근처에서 끝나 어깨에 닿지 않는 기장이에요.' },
          { ko: '중단발', en: 'medium-length hair that ends at the shoulders or collarbone', syn: ['어깨 기장', '쇄골 기장'], def: '머리끝이 어깨나 쇄골 근처에 닿는 중간 기장이에요.' },
          { ko: '긴머리', en: 'long hair that falls well below the shoulders to the chest or back', syn: ['장발', '롱헤어'], def: '머리끝이 어깨를 훌쩍 넘어 가슴이나 등까지 내려오는 기장이에요.' },
        ],
      },
      {
        key: 'cut', label: '커트',
        templates: ['a photo of a person with a {}', 'a hairstyle photo of a {}'],
        labels: [
          { ko: '레이어드컷', en: 'layered haircut with soft long layers framing the face', syn: ['버터플라이컷', '롱 레이어드', '레이어드 단발'], def: '얼굴선을 따라 길고 부드러운 층을 낸 커트로, 허쉬컷보다 층이 차분해요.' },
          { ko: '허쉬컷', en: 'hush cut, a shaggy layered cut with airy wispy textured ends', syn: ['샤기컷', '모던 샤기', '허쉬 숏컷'], def: '정수리부터 층을 많이 내 끝이 가볍게 흩어지는 커트예요.' },
          { ko: '원랭스', en: 'one-length cut, medium or long hair cut evenly to one straight length with no visible layers', syn: ['원랭스컷', '일자머리'], def: '층 없이 머리끝을 한 길이로 고르게 맞춘 중간·긴 기장 커트예요.' },
          { ko: '칼단발', en: 'blunt one-length bob cut in a sharp straight horizontal line at the jaw or chin with heavy flat ends and no layers', syn: ['똑단발', '일자단발', '블런트컷'], def: '턱선에서 층 없이 일자로 잘라 끝선이 반듯하고 무거운 단발이에요.' },
          { ko: '태슬컷', en: 'tassel cut, a near one-length bob or lob whose ends are texturized into soft slightly uneven feathery tips', def: '일자 단발에 가깝지만 끝을 가볍게 쳐내 술 장식처럼 살짝 흩어지는 커트예요.' },
          { ko: '보브컷', en: 'classic rounded bob around the jaw whose ends curve softly under toward the neck in a smooth dome-shaped silhouette', syn: ['프렌치 보브', 'C컬 단발', '슬릭 보브'], def: '턱선 길이에서 끝이 안쪽으로 둥글게 말려 전체가 둥근 실루엣인 단발이에요.' },
          { ko: '히메컷', en: 'hime cut, long straight hair with blunt bangs and straight cheek-length side locks', syn: ['공주컷'], def: '일자 앞머리와 볼 길이에서 일자로 끊은 옆머리가 특징인 긴 생머리 커트예요.' },
          { ko: '울프컷', en: 'wolf cut, a choppy shag with short heavy layers on the crown, rough textured ends and a longer thin back', def: '정수리 쪽은 짧고 풍성하게, 뒷머리는 길고 가늘게 남겨 끝이 거친 커트예요.' },
          { ko: '멀릿컷', en: 'mullet haircut with short front and sides and noticeably longer hair left at the back of the neck', syn: ['소프트 멀릿', '베이비 멀릿'], def: '앞과 옆은 짧고 목덜미 쪽 뒷머리만 눈에 띄게 길게 남긴 커트예요.' },
          { ko: '픽시컷', en: 'pixie cut, a very short cropped feminine haircut', def: '귀와 목선이 드러날 만큼 아주 짧게 자른 여성 숏커트예요.' },
          { ko: '빅시컷', en: 'bixie cut, a short shaggy cut between a pixie and a bob with ears partly covered and wispy face-framing layers', syn: ['픽시보브'], def: '픽시컷과 보브컷 사이 길이로, 귀를 살짝 덮고 가벼운 층을 낸 숏커트예요.' },
          { ko: '댄디컷', en: "dandy cut, a neat short men's haircut with a soft fringe covering the forehead", syn: ['시스루댄디', '덮머', '바가지머리'], def: '앞머리를 내려 이마를 덮고 전체를 단정하게 다듬은 남자 커트예요.' },
          { ko: '쉼표머리', en: "comma hair, a men's side-parted fringe whose front lock curls inward into a comma shape over the forehead", syn: ['쉼표펌', '콤마헤어'], def: '옆 가르마를 탄 앞머리 끝이 이마 쪽으로 말려 쉼표 모양이 되는 남자 머리예요.' },
          { ko: '가르마펌', en: "men's side-part perm with a clear side part, the forehead exposed and soft permed volume swept to one side, short sides", syn: ['가르마컷', '2:8 가르마'], def: '옆 가르마로 이마를 드러내고 펌으로 볼륨을 준 윗머리를 한쪽으로 넘긴 남자 머리예요.' },
          { ko: '애즈펌', en: "men's A's perm, a softly permed fringe parted in the middle and curving outward to both sides like curtains, short sides", syn: ['애즈컷', '센터파팅'], def: '가운데 가르마로 나눈 앞머리를 펌으로 양옆 바깥으로 둥글게 넘긴 남자 머리예요.' },
          { ko: '가일컷', en: "men's short cut where one side of the fringe is swept up off the forehead and the other side falls over the forehead", syn: ['숏가일', '가일펌'], def: '앞머리 한쪽은 올려 이마를 드러내고 다른 쪽은 내려 이마를 덮는 남자 커트예요.' },
          { ko: '리프컷', en: "leaf cut, a men's medium-length cut with long side-parted bangs that sweep outward in a curved leaf shape past the temples", def: '긴 앞머리를 옆 가르마로 나눠 관자놀이 바깥으로 나뭇잎처럼 휘어 넘긴 남자 커트예요.' },
          { ko: '아이비리그컷', en: "ivy league cut, a short men's haircut with a neat side part, short tapered sides and a slightly longer top brushed to the side", def: '옆머리는 짧게, 윗머리는 조금 길게 남겨 옆 가르마로 단정히 넘긴 짧은 남자 커트예요.' },
          { ko: '투블럭컷', en: 'two block cut with short shaved sides and longer hair on top', syn: ['언더컷', '투블럭 다운펌'], def: '옆·뒷머리는 짧게 밀고 윗머리는 길게 남겨 경계가 뚜렷하게 나뉘는 커트예요.' },
          { ko: '크롭컷', en: "men's textured crop cut, a very short choppy textured top with a short straight fringe across the forehead", syn: ['텍스처드 크롭', '세미크롭', '시저컷'], def: '아주 짧은 윗머리에 질감을 주고 앞머리를 이마 위에서 짧게 일자로 자른 남자 커트예요.' },
          { ko: '페이드컷', en: "skin fade, a men's haircut whose sides blend gradually from skin-short at the bottom to longer hair on top", syn: ['스킨페이드', '테이퍼 페이드', '바버컷'], def: '옆과 뒷머리가 아래쪽 맨살에서 위로 갈수록 점점 길어지게 이어지는 커트예요.' },
          { ko: '포마드·슬릭백', en: 'slicked back hair or a pompadour styled with pomade', syn: ['올백', '리젠트'], def: '왁스나 포마드를 발라 머리를 뒤로 매끈하게 넘기거나 앞머리를 높이 세워 넘긴 스타일이에요.' },
          { ko: '버즈컷', en: 'buzz cut, hair clipped very short all over the head', syn: ['크루컷', '삭발'], def: '머리 전체를 바리캉으로 아주 짧고 고르게 민 커트예요.' },
          { ko: '모히칸', en: 'mohawk with shaved sides and a strip of spiked hair in the middle', def: '양옆을 밀고 머리 가운데만 띠처럼 남겨 뾰족하게 세운 스타일이에요.' },
          { ko: '머쉬룸컷', en: 'mushroom cut, a rounded bowl-shaped haircut with a heavy fringe curving around the head', syn: ['바가지머리', '보울컷'], def: '버섯처럼 둥근 실루엣으로 앞머리와 옆머리가 한 선으로 이어지는 커트예요.' },
          { ko: 'A라인 보브', en: 'A-line graduated bob that is shorter at the back and longer toward the front', syn: ['그래주에이션 보브', '앞머리 긴 단발'], def: '뒤가 짧고 앞으로 올수록 길어지는 단발로 옆에서 보면 A자 사선이 생겨요.' },
          { ko: '레이어드 숏컷', en: 'short layered haircut with textured choppy layers on top and around the crown', syn: ['숏 레이어드', '숏 샤기'], def: '짧은 기장에 층을 내 윗머리에 볼륨과 움직임을 준 커트예요.' },
          { ko: 'V라인컷', en: 'long hair cut into a V-shaped point at the back ends', syn: ['V컷', '뾰족 끝선'], def: '뒷머리 끝선이 가운데로 모여 V자로 뾰족하게 떨어지는 긴 머리 커트예요.' },
          { ko: '언더컷', en: 'undercut hairstyle with the sides and back shaved short and a long disconnected top', syn: ['디스커넥티드 컷', '사이드 쉐이브'], def: '옆과 뒤를 바싹 밀고 윗머리는 길게 남겨 경계가 뚜렷한 커트예요.' },
          { ko: '테이퍼컷', en: 'men\'s tapered haircut that gradually gets shorter down the sides and nape with a neat outline', syn: ['테이퍼드', '내추럴 테이퍼'], def: '옆과 뒷목으로 갈수록 자연스럽게 짧아지되 페이드보다 길이를 남긴 커트예요.' },
          { ko: '숏 보브', en: 'very short chin-length or above-chin French bob haircut', syn: ['프렌치 보브', '귀밑 단발'], def: '턱선보다 짧게 귀밑에서 끝나는 아주 짧은 단발이에요.' },
        ],
      },
      {
        key: 'styling', label: '연출',
        templates: ['a photo of a person with {}', 'a hairstyle with {}'],
        labels: [
          { ko: '풀어내린 머리', en: 'hair worn down loose', tag: '', def: '묶거나 올리지 않고 그대로 풀어 내린 머리예요.' },
          { ko: '포니테일', en: 'hair tied back in a ponytail', syn: ['하이포니테일', '로우포니테일'], def: '머리를 뒤로 모아 한 갈래로 묶어 늘어뜨린 스타일이에요.' },
          { ko: '똥머리', en: 'hair tied up in a messy loose bun with flyaways on top or at the back of the head', syn: ['메시번'], def: '머리를 정수리나 뒤통수에 대충 말아 올려 잔머리가 삐져나온 둥근 묶음 머리예요.' },
          { ko: '슬릭번', en: 'a sleek bun, hair pulled back tightly and smoothly with no flyaways into a neat compact bun', syn: ['클린번', '로우번', '발레리나 번'], def: '잔머리 없이 머리를 매끈하게 당겨 작고 단단하게 말아 묶은 머리예요.' },
          { ko: '반묶음', en: 'half-up half-down hair', syn: ['하프업'], def: '윗머리만 모아 묶고 아랫머리는 풀어 둔 스타일이에요.' },
          { ko: '양갈래', en: 'pigtails, hair tied into two sections on both sides', syn: ['만두머리', '트윈테일'], def: '머리를 좌우 두 갈래로 나눠 묶거나 동그랗게 말아 올린 스타일이에요.' },
          { ko: '땋은머리', en: 'braided hair with braids or cornrows', syn: ['디스코머리', '피쉬테일', '콘로우'], def: '머리를 가닥으로 엮어 땋거나 두피에 붙여 촘촘히 땋은 스타일이에요.' },
          { ko: '드레드', en: 'dreadlocks', def: '머리카락을 굵은 밧줄처럼 꼬아 뭉친 가닥이 여러 개 늘어진 스타일이에요.' },
          { ko: '업스타일', en: 'an elegant formal updo for a wedding or event', syn: ['올림머리', '웨딩 업스타일'], def: '결혼식이나 행사용으로 머리 전체를 공들여 정돈해 올린 머리예요.' },
          { ko: '집게핀 헤어', en: 'hair twisted up at the back of the head and held by a large claw clip', syn: ['집게핀 머리', '집게핀 업스타일'], tag: '집게핀헤어', def: '머리를 뒤통수에서 꼬아 올려 큰 집게핀으로 고정한 스타일이에요.' },
          { ko: '사과머리', en: 'front bangs gathered and tied up into a small sprout on top of the forehead', syn: ['앞머리 묶기', '분수머리'], def: '앞머리를 모아 이마 위에서 사과 꼭지처럼 작게 묶어 올린 머리예요.' },
          { ko: '올백', en: 'hair slicked straight back off the forehead with no parting', syn: ['슬릭 올백', '넘긴 머리'], def: '앞머리와 옆머리를 모두 뒤로 넘겨 이마를 다 드러낸 연출이에요.' },
          { ko: '스페이스번', en: 'two space buns, hair twisted into a small bun on each side of the head', syn: ['양갈래 번', '미키마우스 번'], def: '머리를 양쪽으로 나눠 작은 똥머리 두 개를 만든 연출이에요.' },
          { ko: '트위스트 묶음', en: 'hair twisted into rope twists or a twisted half-up style', syn: ['꽈배기 묶음', '로프 트위스트'], def: '머리 다발을 꼬아 만든 꽈배기 모양으로 묶거나 고정한 연출이에요.' },
        ],
      },
      {
        key: 'perm', label: '펌·질감', tagSuffix: '',
        templates: ['a photo of a person with {}', 'a close-up photo of {}'],
        labels: [
          { ko: '생머리', en: 'sleek straight hair with no curls or waves', syn: ['매직', '스트레이트'], def: '컬이나 웨이브 없이 곧게 뻗은 매끈한 머리예요.' },
          { ko: 'C컬펌', en: 'straight hair with the ends curling inward in a soft c-curl', syn: ['볼륨매직', '안C컬'], def: '곧은 머리의 끝만 안쪽으로 C자처럼 부드럽게 말린 펌이에요.' },
          { ko: '바깥C컬', en: 'flipped ends, hair whose ends curl outward away from the face in a flicked-out curve', syn: ['플립컷', '뻗침 단발'], def: 'C컬펌과 반대로 머리끝이 얼굴 바깥쪽으로 뻗치듯 말린 모양이에요.' },
          { ko: 'S컬펌', en: 'loose flowing s-shaped waves through the hair', syn: ['웨이브펌', '쉐도우펌', '릴리펌'], def: '머리 전체에 S자 모양의 느슨하고 굵은 웨이브가 흐르는 펌이에요.' },
          { ko: '물결펌', en: 'water-wave perm, uniform tight continuous zigzag ripple waves from near the roots to the ends', syn: ['물결 웨이브', 'SS컬펌'], def: '뿌리 가까이부터 끝까지 잔잔한 물결 모양 웨이브가 촘촘하고 고르게 이어지는 펌이에요.' },
          { ko: '빌드펌', en: 'glamorous big voluminous bouncy curls from the mid-lengths', syn: ['엘리자벳펌', '글램펌'], def: '머리 중간부터 크고 탄력 있는 컬을 넣어 볼륨이 풍성한 펌이에요.' },
          { ko: '젤리펌', en: 'jelly perm, bouncy springy medium-sized spiral curls with glossy definition, looser than a hippie perm', syn: ['그레이스펌', '탱글펌'], def: '히피펌보다 굵은 중간 크기 나선 컬이 탱글하고 윤기 있게 살아 있는 펌이에요.' },
          { ko: '히피펌', en: 'hippie perm, small tight voluminous frizzy curls all over', syn: ['베이비펌'], def: '머리 전체에 작고 촘촘한 컬을 넣어 부스스하게 부풀린 펌이에요.' },
          { ko: '내추럴 곱슬', en: 'natural curly or coily afro-textured hair', syn: ['곱슬머리', '아프로'], def: '타고난 곱슬이나 아주 촘촘하게 말린 아프로 질감의 머리예요.' },
          { ko: '매직 스트레이트', en: 'magic straight perm, chemically straightened perfectly sleek hair with inward volume at the ends', syn: ['볼륨매직', '스트레이트 매직', '매직'], def: '약으로 곧게 펴면서 끝에 안쪽 볼륨만 살린 매끈한 생머리 펌이에요.' },
          { ko: '다운펌', en: 'men\'s down perm that flattens the sides so the hair lies close to the head', syn: ['옆머리 다운펌', '볼륨 다운'], def: '뜨는 옆머리나 뒷머리를 눌러 두상에 붙게 만드는 펌이에요.' },
          { ko: '셋팅펌', en: 'setting perm with big bouncy C-curl or S-curl volume made with hot rollers', syn: ['열펌', '볼륨 셋팅'], def: '열 롤로 굵고 탄력 있는 볼륨 컬을 만드는 펌이에요.' },
          { ko: '쉐도우펌', en: 'men\'s shadow perm with soft natural wave and volume on the top', syn: ['남자 쉐도우펌', '내추럴 펌'], def: '남성 윗머리에 자연스러운 결과 볼륨을 주는 약한 펌이에요.' },
          { ko: '글램펌', en: 'glam perm with large loose romantic waves on long hair', syn: ['바디펌', '로맨틱 웨이브'], def: '긴 머리에 굵고 느슨한 웨이브를 넣어 풍성하게 흐르는 펌이에요.' },
        ],
      },
      {
        key: 'bangs', label: '앞머리',
        templates: ['a photo of a person with {}', 'a hairstyle with {}'],
        labels: [
          { ko: '앞머리 없음', en: 'no bangs, hair swept away from a visible forehead', tag: '', syn: ['깐머리', '이마 노출'], def: '이마를 덮는 머리 없이 모두 뒤나 옆으로 넘겨 이마가 훤히 드러난 상태예요.' },
          { ko: '풀뱅', en: 'full thick blunt bangs covering the forehead', syn: ['일자 앞머리'], def: '숱을 많이 남겨 이마를 완전히 덮는 두꺼운 일자 앞머리예요.' },
          { ko: '처피뱅', en: 'choppy micro bangs, very short blunt bangs cut well above the eyebrows at mid-forehead', syn: ['마이크로뱅', '숏뱅'], def: '눈썹이 훤히 보이도록 이마 중간 높이에서 짧게 자른 앞머리예요.' },
          { ko: '시스루뱅', en: 'thin wispy see-through bangs', syn: ['위스피뱅', '에어뱅'], def: '숱을 적게 내 이마가 비쳐 보이는 가벼운 앞머리예요.' },
          { ko: 'U뱅', en: 'u-shaped bangs, a wispy fringe shortest in the center at eyebrow level that grows longer toward the temples in a soft arch', syn: ['U자 앞머리'], def: '가운데는 눈썹 길이로 가장 짧고 양옆으로 갈수록 길어져 U자를 그리는 앞머리예요.' },
          { ko: '사이드뱅', en: 'side-swept bangs brushed to one side', syn: ['깻잎머리', '옆 가르마'], def: '앞머리를 한쪽으로 비스듬히 넘겨 이마 일부를 덮은 모양이에요.' },
          { ko: '커튼뱅', en: 'curtain bangs parted in the middle framing the face', syn: ['가운데 가르마'], def: '가운데에서 갈라 양옆으로 커튼처럼 내려 얼굴선을 감싸는 앞머리예요.' },
          { ko: '애교머리', en: 'face-framing wisps, a few short loose strands falling along the temples and cheeks while the forehead stays open', syn: ['애교뱅', '잔머리'], def: '이마는 드러내고 관자놀이와 볼 옆으로 짧은 잔머리 몇 가닥만 내린 모양이에요.' },
          { ko: '확인 불가', en: 'the back of the head seen from behind, the forehead is not visible', hidden: true, def: '뒷모습처럼 이마가 보이지 않아 앞머리를 판단할 수 없을 때 쓰는 값이에요.' },
          { ko: '베이비뱅', en: 'very short baby bangs cut high above the eyebrows', syn: ['마이크로 뱅', '짧은 앞머리'], def: '눈썹보다 훨씬 위로 짧게 자른 앞머리예요.' },
          { ko: '와이드뱅', en: 'wide full bangs that extend past the temples across the whole forehead', syn: ['넓은 앞머리', '풀 와이드 뱅'], def: '관자놀이 너머까지 넓게 잡아 이마 전체를 덮는 앞머리예요.' },
          { ko: '넘긴 앞머리', en: 'long bangs swept back or pinned up to show the forehead', syn: ['올린 앞머리', '핀 앞머리'], def: '앞머리가 있지만 뒤로 넘기거나 핀으로 올려 이마를 드러낸 상태예요.' },
        ],
      },
      {
        key: 'color', label: '컬러',
        templates: ['a photo of a person with {}', 'a hair color photo of {}'],
        labels: [
          { ko: '흑발', en: 'natural jet black hair', tone: 'neutral', def: '빛을 받아도 갈색기가 거의 없는 짙은 검은색 머리예요.' },
          { ko: '블루블랙', en: 'blue-black hair, black with a cool blue sheen', tone: 'cool', syn: ['미드나잇블루'], def: '검은색 바탕에 빛을 받으면 푸른 기가 도는 머리색이에요.' },
          { ko: '초코브라운', en: 'rich dark chocolate brown hair', tone: 'warm', syn: ['다크브라운'], def: '검은색에 가까울 만큼 진한 초콜릿빛 갈색이에요.' },
          { ko: '밀크브라운', en: 'soft light milky beige brown hair', tone: 'neutral', syn: ['밀크티브라운', '모카브라운'], def: '우유를 섞은 듯 부드럽고 밝은 베이지빛 갈색이에요.' },
          { ko: '애쉬베이지', en: 'ash beige hair, a light muted greyish beige between light brown and blonde, matte and low-saturation', tone: 'cool', syn: ['밀크베이지', '샌드베이지'], def: '밝은 갈색과 금발 사이의, 회색빛이 도는 차분한 베이지색이에요.' },
          { ko: '애쉬브라운', en: 'cool ash brown hair with a greyish muted tone', tone: 'cool', def: '붉은 기를 빼 회색빛이 도는 차분한 갈색이에요.' },
          { ko: '카키브라운', en: 'khaki brown hair with an olive greenish tint', tone: 'cool', syn: ['매트브라운', '올리브브라운'], def: '갈색에 올리브처럼 옅은 초록빛이 도는 머리색이에요.' },
          { ko: '골드브라운', en: 'warm golden caramel brown hair', tone: 'warm', syn: ['카라멜브라운', '테디베어 브라운'], def: '캐러멜처럼 노란 금빛이 도는 따뜻한 갈색이에요.' },
          { ko: '오렌지브라운', en: 'orange copper brown hair', tone: 'warm', syn: ['코퍼브라운'], def: '구리처럼 주황빛이 뚜렷하게 돌아 골드브라운보다 붉어 보이는 갈색이에요.' },
          { ko: '핑크브라운', en: 'rose brown hair, a soft muted brown with a subtle pinkish rosy tint', tone: 'neutral', syn: ['로즈브라운', '코랄브라운'], def: '차분한 갈색에 은은한 분홍빛이 도는 머리색이에요.' },
          { ko: '레드와인', en: 'wine red burgundy hair', tone: 'cool', syn: ['체리브라운', '레드브라운', '버건디'], def: '와인이나 버건디처럼 갈색이 섞인 깊고 어두운 붉은색 머리예요.' },
          { ko: '애쉬블론드', en: 'cool ash or platinum blonde hair', tone: 'cool', syn: ['플래티넘', '백금발'], def: '노란 기를 빼 백금처럼 하얗게 밝은 금발이에요.' },
          { ko: '골드블론드', en: 'warm golden honey blonde hair', tone: 'warm', syn: ['허니블론드'], def: '꿀처럼 노란 금빛이 도는 밝은 금발로, 애쉬블론드보다 따뜻해 보여요.' },
          { ko: '애쉬그레이', en: 'ash grey or silver hair', tone: 'cool', syn: ['실버', '백발 염색'], def: '흰머리처럼 노란 기 없이 회색이나 은빛으로 물들인 머리예요.' },
          { ko: '핑크·라벤더', en: 'pastel pink or lavender dyed hair', tone: 'cool', tag: '핑크염색', def: '파스텔 톤의 연분홍이나 연보라로 물들인 머리예요.' },
          { ko: '블루·퍼플', en: 'vivid blue or purple dyed hair', tone: 'cool', tag: '블루염색', def: '파스텔보다 진하고 선명한 파란색이나 보라색으로 물들인 머리예요.' },
          { ko: '그린·민트', en: 'green or mint dyed hair', tone: 'cool', tag: '민트염색', def: '초록색이나 푸른빛이 도는 민트색으로 물들인 머리예요.' },
          { ko: '비비드 레드', en: 'vivid bright red dyed hair', tone: 'warm', def: '와인색보다 밝고 선명한 빨간색으로 물들인 머리예요.' },
          { ko: '로즈골드', en: 'rose gold hair, a pinkish blonde with warm golden peach shimmer', tone: 'warm', syn: ['로즈 블론드', '피치 핑크'], def: '분홍빛이 도는 따뜻한 금발로 복숭아 광택이 나는 색이에요.' },
          { ko: '플래티넘·화이트', en: 'platinum or white blonde hair, bleached to a nearly white icy pale color', tone: 'cool', syn: ['백금발', '화이트 블론드', '아이스 블론드'], def: '탈색으로 거의 흰색에 가깝게 밝힌 차가운 백금발이에요.' },
          { ko: '카라멜브라운', en: 'caramel brown hair, a warm golden medium brown with honey tones', tone: 'warm', syn: ['허니브라운', '토피브라운'], def: '꿀처럼 노란빛이 도는 따뜻한 중간 갈색이에요.' },
          { ko: '코퍼·오렌지', en: 'copper or bright orange ginger hair color', tone: 'warm', syn: ['구리색', '진저', '오렌지 염색'], def: '구리처럼 선명한 주황빛 머리색이에요.' },
        ],
      },
      {
        key: 'colorTech', label: '컬러 기법',
        templates: ['a photo of a person with {}', 'a hair color photo of {}'],
        labels: [
          { ko: '전체 염색', en: 'hair in one single even color from root to tip', tag: '', def: '뿌리부터 끝까지 한 가지 색으로 고르게 물들인 머리예요.' },
          { ko: '브릿지', en: 'one or a few bold chunky streaks of contrasting color, often a bright strand at the front framing the face', syn: ['앞머리 브릿지', '머니피스'], def: '앞머리 쪽 등 일부 가닥에만 굵게 다른 색을 넣어 눈에 띄게 한 염색이에요.' },
          { ko: '하이라이트', en: 'highlights, many fine thin streaks of lighter blonde or caramel color woven evenly through darker hair', syn: ['위빙', '부분탈색'], def: '어두운 머리 전체에 밝은 색의 가는 가닥을 촘촘하게 골고루 섞은 염색이에요.' },
          { ko: '발레아쥬', en: 'balayage, soft hand-painted lighter color through the lengths', syn: ['컬러 멜팅'], def: '붓으로 칠하듯 머리 중간부터 밝은 색을 자연스럽게 번지게 넣은 염색이에요.' },
          { ko: '옴브레', en: 'ombre hair, dark roots gradually fading to a light color at the ends', syn: ['그라데이션 염색'], def: '뿌리는 어둡고 끝으로 갈수록 점점 밝아지는 그라데이션 염색이에요.' },
          { ko: '이너컬러', en: 'hidden inner color, a bright color peeking from the underneath layer', syn: ['시크릿투톤', '히든컬러'], def: '겉머리는 그대로 두고 안쪽 머리에만 밝은 색을 넣어 살짝 비치게 한 염색이에요.' },
          { ko: '투톤', en: 'two-tone hair split into two distinct colors', syn: ['반반염색'], def: '머리를 위아래나 좌우로 나눠 서로 다른 두 색으로 물들인 염색이에요.' },
          { ko: '머니피스', en: 'money piece highlights, two bright face-framing strands at the front hairline', syn: ['페이스 프레이밍', '앞머리 브릿지'], def: '얼굴 양옆 앞머리 가닥만 밝게 물들여 얼굴을 감싸는 기법이에요.' },
          { ko: '로우라이트', en: 'lowlights, darker strands woven into lighter hair for depth', syn: ['어두운 브릿지', '섀도 하이라이트'], def: '밝은 머리 사이에 어두운 가닥을 넣어 깊이를 주는 기법이에요.' },
          { ko: '루트 섀도우', en: 'root shadow or shadow root, darker roots melting into lighter lengths', syn: ['뿌리 염색 생략', '섀도 루트'], def: '뿌리를 어둡게 두고 아래로 갈수록 밝아지게 이어 붙인 기법이에요.' },
        ],
      },
      {
        key: 'tone', label: '톤', tagSuffix: '염색',
        templates: ['a photo of a person with {}', '{}'],
        labels: [
          { ko: '쿨톤', en: 'cool-toned hair color with ashy grey, blue or violet undertones and no warmth', def: '붉거나 노란 기 없이 회색·푸른빛·보랏빛이 도는 차가운 계열의 머리색이에요.' },
          { ko: '웜톤', en: 'warm-toned hair color with golden, orange, copper or reddish undertones', def: '금빛·주황빛·붉은빛이 도는 따뜻한 계열의 머리색이에요.' },
          { ko: '뉴트럴', en: 'natural neutral-toned hair color, neither warm nor ashy', tag: '', def: '따뜻한 기운도 회색빛도 두드러지지 않는 중간 계열의 머리색이에요.' },
        ],
      },
      {
        key: 'mood', label: '분위기', tagSuffix: '헤어',
        templates: ['a photo of a {} hairstyle', 'a {} hair look'],
        labels: [
          { ko: '청순', en: 'innocent pure and soft-looking', def: '꾸밈이 적은 생머리나 부드러운 컬로 맑고 순한 인상을 주는 분위기예요.' },
          { ko: '러블리', en: 'cute lovely and girly', def: '동그란 컬, 앞머리, 리본 같은 요소로 귀엽고 사랑스러운 인상을 주는 분위기예요.' },
          { ko: '시크', en: 'chic cool and sophisticated', def: '장식 없이 매끈하고 깔끔한 선으로 차갑고 도회적인 인상을 주는 분위기예요.' },
          { ko: '힙', en: 'hip edgy bold street-style', def: '개성 있는 커트나 강한 색으로 스트리트 패션 같은 과감한 인상을 주는 분위기예요.' },
          { ko: '내추럴', en: 'natural effortless and casual', syn: ['꾸안꾸'], def: '힘을 많이 주지 않은 듯 자연스럽게 흐트러진 편안한 분위기예요.' },
          { ko: '단정·오피스', en: 'neat tidy and professional', tag: '단정한헤어', def: '잔머리 없이 깔끔하게 정돈해 출근이나 면접에 어울리는 분위기예요.' },
          { ko: '우아·고급', en: 'elegant glamorous and luxurious', tag: '고급스러운헤어', syn: ['올드머니'], def: '윤기 있는 굵은 웨이브나 정돈된 올림머리로 고급스럽고 차분한 인상을 주는 분위기예요.' },
          { ko: '레트로', en: 'retro vintage', def: '옛날 영화나 사진 속 같은 컬, 앞머리, 볼륨으로 지난 유행을 떠올리게 하는 분위기예요.' },
          { ko: '글램·화려', en: 'glamorous voluminous red-carpet hairstyle', syn: ['화려한', '레드카펫'], def: '볼륨과 광택이 큰, 파티나 무대에 어울리는 화려한 분위기예요.' },
          { ko: '보이시', en: 'boyish tomboy short hairstyle on a woman', syn: ['톰보이', '중성적'], def: '짧고 중성적인 느낌으로 소년 같은 분위기예요.' },
          { ko: '스포티·캐주얼', en: 'sporty casual easy hairstyle for an active look', syn: ['캐주얼', '활동적'], def: '활동하기 편하고 가벼운 운동복 차림에 어울리는 분위기예요.' },
          { ko: '펑크·록', en: 'punk rock edgy hairstyle with spikes, shaved parts or wild texture', syn: ['락시크', '그런지'], def: '세운 머리나 밀어낸 부분이 있는 거칠고 반항적인 분위기예요.' },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────── 네일
  nail: {
    label: '네일',
    icon: '💅',
    detect: [
      'a close-up photo of fingernails with nail polish',
      'a photo of a manicure with nail art',
      'a photo of a hand showing painted nails',
      'a photo of painted toenails, a pedicure on bare feet',
    ],
    groups: [
      {
        key: 'shape', label: '쉐입', tagSuffix: '쉐입',
        templates: ['a close-up photo of {} nails', 'a manicure with {} nail shape'],
        labels: [
          { ko: '라운드', en: 'short rounded', def: '손톱 끝을 짧게 자르고 손끝 모양을 따라 둥글게 다듬은 모양이에요.' },
          { ko: '오벌', en: 'oval shaped', def: '손톱 끝을 달걀처럼 길쭉하고 둥글게 다듬은 모양이에요.' },
          { ko: '스퀘어', en: 'square shaped flat-tipped', syn: ['숏스퀘어'], def: '손톱 끝을 일자로 평평하게 자르고 모서리를 각지게 남긴 모양이에요.' },
          { ko: '라운드스퀘어', en: 'squoval, square with softly rounded corners', syn: ['스퀘어오벌', '스쿼벌'], def: '끝은 일자로 평평하되 양쪽 모서리만 둥글게 다듬은 모양이에요.' },
          { ko: '아몬드', en: 'almond shaped tapered', def: '옆선이 끝으로 갈수록 좁아져 아몬드처럼 둥글게 뾰족해지는 모양이에요.' },
          { ko: '코핀', en: 'coffin ballerina shaped, long tapered with a flat squared tip', syn: ['발레리나'], def: '길게 기른 손톱이 끝으로 좁아지다가 끝만 일자로 평평하게 잘린 모양이에요.' },
          { ko: '스틸레토', en: 'sharp pointed stiletto', def: '끝으로 갈수록 가늘어져 송곳처럼 뾰족하게 마무리한 모양이에요.' },
          { ko: '플레어', en: 'flared duck-shaped, widening outward toward a broad flat tip', syn: ['덕네일'], def: '끝으로 갈수록 오리발처럼 넓게 퍼지고 끝이 평평한 모양이에요.' },
          { ko: '립스틱', en: 'lipstick nail shape cut diagonally like a lipstick tip', syn: ['사선 쉐입', '립스틱 네일'], def: '립스틱 끝처럼 손톱 끝을 사선으로 자른 모양이에요.' },
        ],
      },
      {
        key: 'length', label: '길이',
        templates: ['a close-up photo of {}', 'a manicure on {}'],
        labels: [
          { ko: '숏네일', en: 'short nails trimmed at or just above the fingertip', syn: ['짧은 손톱'], def: '손톱 끝이 손가락 끝과 비슷하거나 살짝 넘는 짧은 길이예요.' },
          { ko: '미디엄', en: 'medium length nails', tag: '', def: '손톱이 손가락 끝을 조금 넘어 자란 중간 길이예요.' },
          { ko: '롱네일', en: 'long nails extending well past the fingertip, gel or acrylic extensions', syn: ['연장', '젤연장'], def: '손가락 끝을 훌쩍 넘을 만큼 길게 기르거나 연장한 손톱이에요.' },
        ],
      },
      {
        key: 'color', label: '컬러', tagSuffix: '네일',
        templates: ['a close-up photo of {} nails', 'a manicure in {}'],
        labels: [
          { ko: '누드·베이지', en: 'nude beige', tone: 'warm', tag: '누드네일', syn: ['누디', '스킨톤', '밀크티 베이지'], def: '피부색과 비슷한 차분한 베이지 계열 색이에요.' },
          { ko: '밀키화이트', en: 'milky white sheer translucent', tone: 'neutral', def: '우유를 탄 듯 반투명하게 비치는 흰색이에요.' },
          { ko: '화이트', en: 'opaque solid pure white', tone: 'neutral', syn: ['퓨어화이트'], def: '속이 비치지 않게 꽉 채운 새하얀 색이에요.' },
          { ko: '연핑크', en: 'soft baby pink', tone: 'cool', syn: ['베이비핑크', '밀키핑크'], def: '아기 볼처럼 연하고 우윳빛이 살짝 도는 부드러운 분홍색이에요.' },
          { ko: '핫핑크', en: 'bright hot pink', tone: 'cool', def: '연핑크보다 훨씬 진하고 선명한 분홍색이에요.' },
          { ko: '코랄·피치', en: 'warm coral or peach apricot', tone: 'warm', tag: '코랄네일', syn: ['살구', '피치'], def: '주황빛이 섞인 산호색이나 복숭아·살구색이에요.' },
          { ko: '레드', en: 'classic red', tone: 'neutral', def: '버건디보다 밝고 선명한 기본 빨간색이에요.' },
          { ko: '버건디', en: 'deep burgundy wine', tone: 'cool', syn: ['와인', '블랙체리'], def: '와인이나 블랙체리처럼 검붉고 깊어 레드보다 어두운 빨간색이에요.' },
          { ko: '블랙', en: 'black', tone: 'neutral', def: '다른 색이 섞이지 않아 빛을 받아도 어둡게 보이는 짙은 검은색이에요.' },
          { ko: '그레이', en: 'soft grey, milky grey or charcoal grey', tone: 'cool', syn: ['밀크그레이', '차콜'], def: '연한 우윳빛 회색부터 짙은 숯색까지의 회색 계열이에요.' },
          { ko: '실버', en: 'metallic silver', tone: 'cool', def: '은수저처럼 금속 광택이 나며 빛을 반사하는 은색이에요.' },
          { ko: '골드', en: 'metallic gold', tone: 'warm', def: '금반지처럼 금속 광택이 나며 빛을 반사하는 금색이에요.' },
          { ko: '네이비·블루', en: 'navy or royal blue', tone: 'cool', tag: '블루네일', syn: ['코발트', '로열블루'], def: '밤하늘 같은 짙은 남색이나 선명하고 진한 파란색이에요.' },
          { ko: '하늘색', en: 'light sky blue', tone: 'cool', syn: ['아이스블루', '베이비블루'], def: '맑은 하늘이나 얼음처럼 연하고 시원해 보이는 밝은 파란색이에요.' },
          { ko: '민트·그린', en: 'pastel mint, pistachio or fresh bright green', tone: 'cool', tag: '민트네일', syn: ['피스타치오'], def: '피스타치오나 민트처럼 연한 파스텔 초록부터 밝은 초록까지의 색이에요.' },
          { ko: '올리브·카키', en: 'muted olive green or khaki, a dusty dark green', tone: 'warm', tag: '카키네일', syn: ['카키', '세이지'], def: '회색과 갈색이 섞인 듯 탁하고 어두운 초록색이에요.' },
          { ko: '라벤더·퍼플', en: 'lavender or purple', tone: 'cool', tag: '라벤더네일', syn: ['라일락'], def: '연보라색부터 진한 보라색까지의 보라 계열이에요.' },
          { ko: '버터옐로', en: 'soft creamy pastel butter yellow', tone: 'warm', syn: ['파스텔옐로', '레몬옐로'], def: '버터처럼 부드럽고 크림빛이 도는 연노란색이에요.' },
          { ko: '오렌지', en: 'bright orange or burnt terracotta orange', tone: 'warm', syn: ['테라코타', '탠저린'], def: '선명한 주황색이나 벽돌빛이 도는 테라코타 주황색이에요.' },
          { ko: '네온', en: 'fluorescent neon highlighter pink, lime or electric blue', tone: 'neutral', syn: ['형광'], def: '형광펜처럼 눈에 확 띄는 형광 분홍·연두·파랑 같은 색이에요.' },
          { ko: '브라운·모카', en: 'brown mocha', tone: 'warm', tag: '모카네일', syn: ['모카무스', '초콜릿', '카라멜'], def: '초콜릿이나 모카커피처럼 따뜻한 갈색 계열이에요.' },
          { ko: '테라코타·브릭', en: 'terracotta brick orange-brown', tone: 'warm', syn: ['벽돌색', '러스트'], def: '벽돌처럼 붉은 주황빛이 도는 갈색이에요.' },
          { ko: '에메랄드·딥그린', en: 'emerald deep green', tone: 'cool', syn: ['딥그린', '포레스트 그린'], def: '에메랄드처럼 진하고 깊은 초록색이에요.' },
          { ko: '더스티로즈', en: 'dusty rose muted pinkish mauve', tone: 'neutral', syn: ['말린장미', '모브핑크'], def: '회기가 섞인 차분한 장밋빛 분홍이에요.' },
          { ko: '샴페인·베이지골드', en: 'champagne beige gold shimmer', tone: 'warm', syn: ['샴페인골드', '베이지 펄'], def: '샴페인처럼 은은한 금빛 베이지예요.' },
        ],
      },
      {
        key: 'design', label: '디자인', tagSuffix: '네일',
        templates: ['a close-up photo of {}', 'nail art with {}'],
        labels: [
          { ko: '원컬러', en: 'plain solid one-color nails with no art', def: '다른 장식 없이 한 가지 색만 고르게 바른 디자인이에요.' },
          { ko: '프렌치', en: 'french tip nails with a contrasting curved line on the tips', def: '손톱 끝에만 다른 색을 둥근 곡선으로 칠한 디자인이에요.' },
          { ko: '마이크로프렌치', en: 'micro french nails with an ultra-thin delicate line of color only at the very edge of the tip', syn: ['헤어라인 프렌치', '얇은 프렌치'], def: '손톱 맨 끝에 머리카락처럼 아주 가는 선만 칠한 프렌치예요.' },
          { ko: '딥프렌치', en: 'deep french nails where the colored tip is very thick and covers a large part of the nail', syn: ['두꺼운 프렌치'], def: '끝 색을 두껍게 칠해 손톱의 절반 가까이를 덮는 프렌치예요.' },
          { ko: '그라데이션', en: 'gradient ombre nails fading between colors', syn: ['옴브레'], def: '한 색에서 다른 색으로 경계 없이 서서히 이어지게 칠한 디자인이에요.' },
          { ko: '글리터', en: 'sparkling chunky glitter nails', syn: ['반짝이', '라메'], def: '굵은 반짝이 입자를 올려 빛에 따라 반짝이는 디자인이에요.' },
          { ko: '자석', en: 'magnetic cat eye gel nails with a sharp shimmering band or line of light across the nail', syn: ['캣아이', '자석젤', '마그네틱'], def: '젤 속 펄을 자석으로 모아 손톱 위에 고양이 눈 같은 빛의 띠를 만든 디자인이에요.' },
          { ko: '벨벳', en: 'velvet magnetic nails with a soft diffused all-over shimmer like brushed velvet and no sharp light band', syn: ['벨벳 자석'], def: '빛의 띠 없이 손톱 전체가 벨벳 천처럼 은은하게 반짝이는 자석 디자인이에요.' },
          { ko: '오로라', en: 'holographic aurora iridescent nails', syn: ['홀로그램', '유니콘 파우더'], def: '보는 각도에 따라 무지갯빛으로 색이 바뀌어 보이는 디자인이에요.' },
          { ko: '크롬', en: 'mirror chrome metallic nails', syn: ['미러파우더', '메탈파우더'], def: '거울처럼 매끈하게 빛을 반사하는 금속 느낌의 디자인이에요.' },
          { ko: '글레이즈드', en: 'glazed donut nails, a sheer milky base with a pearly chrome sheen', syn: ['진주파우더', '펄 파우더'], def: '반투명한 우윳빛 바탕에 진주 같은 광택을 얇게 입혀 도넛 설탕막처럼 보이는 디자인이에요.' },
          { ko: '자개', en: 'iridescent mother-of-pearl shell flakes inlaid on the nails with a pink-green opal shimmer', syn: ['오팔', '나전'], def: '조개껍데기 조각을 박은 듯 분홍·초록빛이 오묘하게 비치는 디자인이에요.' },
          { ko: '시럽', en: 'syrup jelly nails with translucent glossy sheer color', syn: ['젤리', '시어젤리', '맑은네일'], def: '속이 비치는 맑은 색을 시럽처럼 윤기 있게 바른 디자인이에요.' },
          { ko: '워터드롭', en: 'clear glossy 3D water droplets raised on the nail surface like real drops of water', syn: ['물방울네일', '버블네일'], def: '투명한 젤로 손톱 위에 진짜 물방울이 맺힌 듯 볼록하게 올린 디자인이에요.' },
          { ko: '마블', en: 'marble pattern nails with swirls', syn: ['대리석', '잉크마블'], def: '대리석 무늬처럼 여러 색이 소용돌이치며 섞인 디자인이에요.' },
          { ko: '치크', en: 'blush aura nails with a soft blurred airbrushed glow of color in the center of each nail', syn: ['블러셔네일', '오라네일'], def: '손톱 가운데에 볼터치처럼 색을 흐릿하게 번지게 넣은 디자인이에요.' },
          { ko: '파츠', en: 'nails decorated with flat rhinestones, crystals and small studs', syn: ['스톤', '큐빅', '풀스톤'], def: '큐빅이나 스톤 같은 작은 반짝이 장식을 납작하게 붙인 디자인이에요.' },
          { ko: '진주', en: 'nails decorated with small pearls', def: '작은 진주알을 손톱 위에 붙여 장식한 디자인이에요.' },
          { ko: '3D조형', en: 'sculpted raised 3D gel art such as drips, waves, bubbles, shells or petals in relief', syn: ['3D네일', '입체 젤아트'], tag: '3D네일', def: '젤을 볼록하게 쌓아 물결, 방울, 꽃잎 같은 입체 모양을 만든 디자인이에요.' },
          { ko: '크롬하츠', en: 'nails decorated with raised silver 3D gothic cross, heart and chain metal charms', syn: ['메탈 파츠', '십자가 파츠'], def: '은색 십자가·하트·체인 모양의 고딕풍 금속 장식을 입체로 붙인 디자인이에요.' },
          { ko: '드로잉', en: 'hand-painted nail art with detailed drawings', syn: ['핸드페인팅', '아트워크'], def: '붓으로 손톱 위에 그림을 직접 섬세하게 그려 넣은 디자인이에요.' },
          { ko: '캐릭터', en: 'nails with cute cartoon character faces, smiley faces or emoji drawings or charms', syn: ['산리오', '스마일'], def: '만화 캐릭터, 스마일, 이모티콘 얼굴을 그리거나 장식으로 붙인 디자인이에요.' },
          { ko: '과일', en: 'nails painted with small fruit motifs such as cherries, strawberries, lemons or watermelon', syn: ['체리네일', '딸기네일'], def: '체리, 딸기, 레몬, 수박 같은 작은 과일 그림을 넣은 디자인이에요.' },
          { ko: '플라워', en: 'floral flower pattern nails', syn: ['꽃', '압화', '데이지'], def: '꽃을 그리거나 말린 꽃잎을 붙여 꽃무늬를 넣은 디자인이에요.' },
          { ko: '레이스', en: 'nails with a delicate white or black lace pattern of fine floral mesh over a sheer base', def: '비치는 바탕 위에 흰색이나 검은색의 가는 레이스 무늬를 올린 디자인이에요.' },
          { ko: '호피·애니멀', en: 'leopard print nails with brown and black spots, or other animal prints like zebra, cow or snakeskin', tag: '호피네일', syn: ['레오파드', '지브라'], def: '표범 무늬나 얼룩말, 젖소, 뱀 가죽 같은 동물 무늬를 넣은 디자인이에요.' },
          { ko: '체크', en: 'checkered, gingham, tartan plaid or argyle pattern nails', syn: ['깅엄', '타탄', '아가일'], def: '바둑판, 깅엄, 타탄, 아가일 같은 격자무늬를 넣은 디자인이에요.' },
          { ko: '니트·트위드', en: 'nails with a raised 3D cable-knit sweater texture or a speckled woven tweed pattern', tag: '니트네일', syn: ['트위드네일', '스웨터네일'], def: '스웨터 꽈배기 무늬를 볼록하게 올리거나 트위드 천처럼 알록달록한 짜임 무늬를 넣은 디자인이에요.' },
          { ko: '스트라이프', en: 'striped nails with repeated parallel bands of contrasting colors', syn: ['줄무늬'], def: '서로 다른 색의 줄을 나란히 반복해 넣은 줄무늬 디자인이에요.' },
          { ko: '하트·리본', en: 'nails with little hearts or ribbon bows', tag: '리본네일', def: '작은 하트나 리본 모양을 그리거나 붙인 디자인이에요.' },
          { ko: '별', en: 'nails with small star shapes or twinkling stars', syn: ['스타', '별자리'], def: '작은 별이나 반짝이는 별 모양을 그리거나 붙인 디자인이에요.' },
          { ko: '도트', en: 'polka dot nails', syn: ['땡땡이', '폴카도트'], def: '동그란 점을 일정하게 찍은 물방울무늬 디자인이에요.' },
          { ko: '라인아트', en: 'nails with thin minimalist lines, waves or geometric line art', syn: ['실버라인', '물결라인'], def: '가는 선으로 곡선이나 도형을 간결하게 그려 넣은 디자인이에요.' },
          { ko: '에어브러시·블러', en: 'airbrush blurred soft spray nail art', syn: ['블러 네일', '스프레이 아트'], def: '에어브러시로 경계를 흐리게 뿌려 번진 듯한 디자인이에요.' },
          { ko: '멜팅·드리핑', en: 'melting drip nail art with paint dripping down the nail', syn: ['드립 네일', '녹는 네일'], def: '색이 녹아 흘러내리는 모양을 그린 디자인이에요.' },
          { ko: '스월', en: 'swirl wavy curved lines nail art', syn: ['물결 라인', '스월 네일'], def: '구불구불한 곡선이 흐르는 디자인이에요.' },
          { ko: '타이다이', en: 'tie-dye swirled multicolor nail art', syn: ['타이다이 네일', '홀치기'], def: '여러 색이 소용돌이처럼 섞인 타이다이 무늬 디자인이에요.' },
          { ko: '스마일·이모지', en: 'smiley face or emoji nail art', syn: ['스마일 네일', '이모티콘'], def: '스마일이나 이모지 얼굴을 그린 디자인이에요.' },
          { ko: '스테인드글라스', en: 'stained glass nail art with colored panes and dark outlines', syn: ['유리 네일', '글라스 아트'], def: '색유리처럼 검은 선으로 나눈 칸에 색을 채운 디자인이에요.' },
        ],
      },
      {
        key: 'layout', label: '구성',
        templates: ['a photo of a manicure with {}', '{}'],
        labels: [
          { ko: '동일디자인', en: 'all nails painted with the same identical color and design', tag: '', syn: ['풀코트'], def: '모든 손톱을 같은 색과 같은 디자인으로 통일한 구성이에요.' },
          { ko: '원포인트', en: 'plain nails with only one or two accent nails decorated with art', tag: '포인트네일', syn: ['포인트아트'], def: '대부분은 단색으로 두고 한두 개 손톱에만 아트를 넣은 구성이에요.' },
          { ko: '퐁당퐁당', en: 'nails alternating between two or more different solid colors from finger to finger', syn: ['투톤 네일', '컬러 믹스'], def: '손가락마다 두 가지 이상의 단색을 번갈아 칠한 구성이에요.' },
          { ko: '오마카세', en: 'every nail with a different mismatched design, a mix of patterns, colors and charms', syn: ['믹스매치', '미스매치'], def: '손톱마다 색, 무늬, 장식을 모두 다르게 섞은 구성이에요.' },
        ],
      },
      {
        key: 'finish', label: '마감', tagSuffix: '네일',
        templates: ['a close-up photo of nails with {}', 'a manicure with {}'],
        labels: [
          { ko: '유광', en: 'a glossy shiny finish', tag: '', syn: ['물광', '글로시'], def: '표면이 매끈하고 반짝이게 광이 나는 마감이에요.' },
          { ko: '매트', en: 'a flat matte finish with no shine', syn: ['무광'], def: '광택 없이 보송한 무광으로 끝낸 마감이에요.' },
          { ko: '메탈릭', en: 'a reflective metallic finish', def: '금속처럼 빛을 강하게 반사하는 마감이에요.' },
          { ko: '투명·쉬어', en: 'a translucent sheer see-through finish', tag: '투명네일', def: '색이 얇게 비쳐 맨 손톱이 드러나 보이는 마감이에요.' },
          { ko: '펄·쉬머', en: 'a pearly shimmery finish', tag: '펄네일', syn: ['진주광', '미세펄'], def: '고운 펄이 섞여 은은하게 반짝이는 마감이에요.' },
        ],
      },
      {
        key: 'mood', label: '분위기', tagSuffix: '네일',
        templates: ['a photo of {} nails', 'a {} manicure'],
        labels: [
          { ko: '오피스', en: 'simple minimal clean everyday office', syn: ['데일리', '하객네일'], def: '장식을 줄이고 차분한 색을 써 출근이나 하객 자리에도 무난한 분위기예요.' },
          { ko: '청순·러블리', en: 'cute lovely girly soft', tag: '러블리네일', def: '연한 분홍이나 우윳빛에 작은 하트·리본을 더해 귀엽고 여린 분위기예요.' },
          { ko: '화려한', en: 'glamorous elaborate bling', syn: ['블링', '풀파츠'], def: '큐빅, 글리터, 장식을 듬뿍 올려 눈에 확 띄는 분위기예요.' },
          { ko: '시크·힙', en: 'chic dark edgy', tag: '시크네일', syn: ['고딕', '걸크러시'], def: '검정이나 어두운 색, 날카로운 쉐입으로 강하고 차가운 분위기예요.' },
          { ko: '쇠맛', en: 'cold futuristic silver chrome metallic cyber', syn: ['메탈', '에스파 네일'], def: '은색 크롬과 금속 장식으로 차갑고 미래적인 느낌을 낸 분위기예요.' },
          { ko: '키치', en: 'playful kitsch y2k with candy colors, cute 3D charms, cherries, hearts and cartoon motifs', syn: ['Y2K', '팝'], def: '사탕 같은 색과 캐릭터, 체리, 하트 장식으로 장난스럽고 귀엽게 꾸민 분위기예요.' },
          { ko: '여름', en: 'fresh summer with clear jelly, ice blue, coral or neon colors, water drops, fruit or ocean motifs', tag: '여름네일', syn: ['바캉스네일', '청량네일'], def: '맑은 시럽, 하늘색, 코랄, 물방울이나 과일 무늬로 시원하고 상큼한 분위기예요.' },
          { ko: '겨울·홀리데이', en: 'cozy winter holiday christmas with red, green, gold glitter, snowflakes or knit textures', tag: '크리스마스네일', syn: ['겨울네일', '연말네일'], def: '빨강·초록·금색 글리터나 눈송이, 니트 무늬로 연말 느낌을 낸 분위기예요.' },
          { ko: '웨딩', en: 'elegant bridal wedding', syn: ['본식', '브라이덜'], def: '흰색, 우윳빛, 진주 장식으로 결혼식에 어울리게 단아하게 꾸민 분위기예요.' },
          { ko: '봄·파스텔', en: 'spring pastel soft nail look', syn: ['봄 네일', '파스텔'], def: '연한 파스텔로 봄처럼 부드러운 분위기예요.' },
          { ko: '가을·무드', en: 'autumn moody warm-toned nail look', syn: ['가을 네일', '단풍색'], def: '단풍이나 흙색처럼 따뜻하고 차분한 가을 분위기예요.' },
          { ko: '미니멀', en: 'minimal clean simple nail look', syn: ['심플', '깔끔'], def: '장식을 줄여 깔끔하고 단순한 분위기예요.' },
        ],
      },
      {
        key: 'part', label: '부위',
        templates: ['a photo of {}', 'a close-up photo of {}'],
        labels: [
          { ko: '핸드', en: 'painted fingernails on a hand', tag: '', syn: ['손톱', '매니큐어'], def: '발이 아닌 손가락 손톱에 바르거나 꾸민 네일이에요.' },
          { ko: '패디', en: 'painted toenails on bare feet, a pedicure', syn: ['패디큐어', '페디', '발톱네일'], def: '손이 아닌 맨발의 발톱에 바르거나 꾸민 네일이에요.' },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────── 메이크업
  makeup: {
    label: '메이크업',
    icon: '💄',
    detect: [
      'a close-up photo of a face wearing makeup',
      'a beauty photo showing eye makeup and lipstick',
      'a portrait photo focusing on the makeup look',
    ],
    groups: [
      {
        key: 'mood', label: '무드', tagSuffix: '메이크업',
        templates: ['a photo of a face with {} makeup', 'a {} makeup look'],
        labels: [
          { ko: '데일리', en: 'natural minimal everyday no-makeup style', syn: ['클린걸', '꾸안꾸', '투명 메이크업'], def: '피부 결만 정돈하고 색을 최소로 써 화장 안 한 듯 자연스러운 메이크업이에요.' },
          { ko: '청순', en: 'soft innocent fresh pink-toned', syn: ['수채화 메이크업', '첫사랑 메이크업'], def: '연한 분홍빛 위주로 맑고 순한 인상을 주는 메이크업이에요.' },
          { ko: '음영', en: 'soft muted brown contour shading that sculpts the eyes and face', syn: ['모카무스 메이크업', '구운 복숭아'], def: '채도 낮은 갈색으로 눈매와 얼굴에 그림자를 넣어 깊이를 준 메이크업이에요.' },
          { ko: '과즙', en: 'fresh juicy fruity makeup with rosy flushed cheeks and glossy tinted lips', syn: ['러블리', '딸기 메이크업'], def: '발그레한 볼과 촉촉하게 물든 입술로 과일처럼 생기 있어 보이는 메이크업이에요.' },
          { ko: '글램', en: 'glamorous full-coverage evening', syn: ['풀메이크업', '파티 메이크업'], def: '피부를 꼼꼼히 덮고 눈과 입술을 진하게 강조한 저녁·파티용 풀 메이크업이에요.' },
          { ko: '스모키', en: 'dark dramatic smokey eye', def: '눈 주위를 어두운 색으로 번지듯 칠해 눈매를 강하게 만든 메이크업이에요.' },
          { ko: '걸크러시', en: 'fierce confident edgy makeup with sharp winged eyeliner, defined brows, sculpted contour and strong lips', syn: ['센 언니 메이크업', '시크 메이크업'], def: '날렵한 아이라인, 또렷한 눈썹, 셰이딩, 진한 입술로 강한 인상을 준 메이크업이에요.' },
          { ko: '쇠맛', en: 'cold metallic futuristic cyber makeup with silver chrome shimmer and sharp lines', syn: ['메탈릭 메이크업', 'Y3K'], def: '은색 크롬 펄과 날카로운 라인으로 차갑고 금속 같은 느낌을 낸 메이크업이에요.' },
          { ko: 'Y2K', en: 'early-2000s y2k makeup with frosty pastel or icy blue shimmer eyeshadow, frosted pale pink lips and glitter', syn: ['펄 걸 글램', '2000년대 메이크업'], def: '펄 섞인 파스텔·하늘색 섀도와 반짝이는 연분홍 입술로 2000년대 초 느낌을 낸 메이크업이에요.' },
          { ko: '갸루', en: 'japanese gyaru makeup with heavy black eyeliner, thick upper and lower lashes, enlarged round eyes and pale glossy lips', syn: ['데일리 갸루'], def: '진한 검은 아이라인과 위아래 풍성한 속눈썹으로 눈을 크고 동그랗게 만든 일본식 메이크업이에요.' },
          { ko: '고딕·뱀파이어', en: 'dark gothic vampire makeup with pale matte skin, shadowy smoky eyes and deep wine, plum or black lips', tag: '뱀파이어메이크업', syn: ['흑화 메이크업'], def: '창백한 매트 피부에 어두운 눈매와 검붉거나 검은 입술을 더한 메이크업이에요.' },
          { ko: '레트로', en: 'retro classic pin-up makeup with red or brown defined lips, winged liner and matte skin', syn: ['핀업', '90년대 메이크업'], def: '매트한 피부에 날개 아이라인과 또렷한 빨강·갈색 입술로 옛날 느낌을 낸 메이크업이에요.' },
          { ko: '웨딩', en: 'bridal wedding', syn: ['신부화장', '본식 메이크업'], def: '결혼식 신부용으로 피부를 맑게 다듬고 이목구비를 또렷하게 살린 메이크업이에요.' },
          { ko: '아트', en: 'bold artistic colorful stage, festival or face painting', syn: ['무대 메이크업', '페스티벌 메이크업'], def: '무대나 축제용으로 얼굴에 대담한 색과 그림을 넣은 메이크업이에요.' },
          { ko: '할로윈·특수분장', en: 'halloween special-effects makeup with fake blood, wounds, scars, stitches, skull or zombie face paint', tag: '할로윈메이크업', syn: ['특수분장', '좀비 메이크업'], def: '가짜 피, 상처, 꿰맨 자국, 해골 분장처럼 특수 효과를 낸 메이크업이에요.' },
          { ko: '남자 메이크업', en: "subtle men's grooming makeup on a man, with an even smooth complexion, groomed brows and soft brown shading", tag: '남자메이크업', syn: ['남돌 메이크업', '그루밍 메이크업'], def: '남성이 피부 톤을 고르게 하고 눈썹과 갈색 음영만 은은하게 더한 메이크업이에요.' },
          { ko: '러블리·핑크', en: 'lovely pink doll-like makeup', syn: ['핑크 메이크업', '인형 메이크업'], def: '분홍 위주로 사랑스럽고 인형 같은 무드예요.' },
          { ko: '뮤트 브라운', en: 'muted brown low-saturation soft makeup', syn: ['브라운 메이크업', '톤다운'], def: '채도를 낮춘 갈색 계열로 차분하고 성숙한 무드예요.' },
          { ko: '페스티벌', en: 'festival makeup with glitter, gems and bright colors', syn: ['축제 메이크업', '글리터 페스티벌'], def: '글리터와 보석, 선명한 색으로 축제 분위기를 낸 무드예요.' },
          { ko: '노메이크업룩', en: 'no-makeup makeup look with sheer natural skin and minimal color', syn: ['생얼 메이크업', '투명 메이크업'], def: '화장을 안 한 듯 피부결과 혈색만 살린 무드예요.' },
        ],
      },
      {
        key: 'base', label: '피부 표현', tagSuffix: '피부',
        templates: ['a close-up photo of a face with {}', 'makeup with {}'],
        labels: [
          { ko: '물광', en: 'very dewy wet-look glass skin', syn: ['물먹광', '유리알 피부', '글래스 스킨'], def: '물기를 머금은 듯 피부 전체가 유리처럼 촉촉하게 빛나는 표현이에요.' },
          { ko: '윤광', en: 'soft satin healthy glow from within', syn: ['결광', '속광', '새틴'], def: '물광보다 은은하게, 속에서 배어 나오는 듯한 윤기가 도는 피부 표현이에요.' },
          { ko: '세미매트', en: 'natural semi-matte skin', syn: ['블러 피부', '소프트 매트'], def: '번들거림은 잡되 살짝 윤기를 남겨 자연스러운 피부 표현이에요.' },
          { ko: '보송 매트', en: 'flat powdery matte skin with no shine', syn: ['매트 피부', '클라우드 스킨'], def: '광 없이 파우더를 바른 듯 보송하고 평평하게 마무리한 피부 표현이에요.' },
        ],
      },
      {
        key: 'eye', label: '아이섀도',
        templates: ['a close-up photo of eyes with {}', 'eye makeup with {}'],
        labels: [
          { ko: '음영 섀도', en: 'subtle muted brown, mauve or grey shading eyeshadow', tag: '음영섀도', syn: ['브라운 음영', '모브 음영'], def: '갈색, 모브, 회색 같은 차분한 색으로 눈두덩에 은은하게 그림자를 준 섀도예요.' },
          { ko: '스모키', en: 'dark smudged smokey eyeshadow around the whole eye in black, grey, plum or brown', syn: ['펄 스모키', '쿨 스모키'], def: '검정, 회색, 자두색, 갈색 섀도를 눈 전체에 진하게 번지듯 칠한 섀도예요.' },
          { ko: '글리터·펄', en: 'sparkly glitter shimmer eyeshadow', tag: '글리터섀도', syn: ['눈물 메이크업', '펄 섀도'], def: '반짝이는 글리터나 펄 입자가 눈두덩에서 빛나는 섀도예요.' },
          { ko: '핑크·코랄 섀도', en: 'pink, coral, peach or orange toned eyeshadow', tag: '코랄섀도', syn: ['피치 섀도', '오렌지 섀도'], def: '분홍, 코랄, 복숭아, 주황빛으로 눈가를 화사하게 물들인 섀도예요.' },
          { ko: '레드 섀도', en: 'red, brick-red or burgundy eyeshadow, a warm reddish flushed eye area', tag: '레드섀도', syn: ['붉은 섀도', '버건디 섀도'], def: '빨강, 벽돌색, 버건디로 눈가를 붉게 상기된 듯 물들인 섀도예요.' },
          { ko: '블루 섀도', en: 'blue eyeshadow, icy pale blue, sky blue or cobalt', tag: '블루섀도', syn: ['아이시 블루'], def: '얼음처럼 연한 파랑, 하늘색, 코발트 같은 파란색 섀도예요.' },
          { ko: '퍼플 섀도', en: 'purple, lavender or lilac eyeshadow', tag: '퍼플섀도', syn: ['라벤더 섀도', '연보라 섀도'], def: '보라, 라벤더, 연보라색으로 눈가를 물들인 섀도예요.' },
          { ko: '그린·옐로 섀도', en: 'bright green, lime, mint or lemon-yellow eyeshadow', tag: '그린섀도', syn: ['라임 섀도', '연두 섀도'], def: '초록, 연두, 민트, 레몬빛 노랑처럼 밝은 색을 쓴 섀도예요.' },
          { ko: '컬러 섀도', en: 'two or more different bright eyeshadow colors combined on the same eye', syn: ['멀티 컬러 섀도', '무지개 메이크업'], def: '한쪽 눈에 선명한 색을 두 가지 이상 함께 쓴 섀도예요.' },
          { ko: '애교살 강조', en: 'highlighted aegyo-sal, a shimmery puffy under-eye area', tag: '애교살메이크업', def: '눈 바로 아래 도톰한 애교살에 펄을 발라 볼록하게 보이게 한 표현이에요.' },
          { ko: '눈앞머리 하이라이트', en: 'a bright shimmering highlight spot on the inner corners of the eyes', tag: '눈앞머리하이라이터', syn: ['앞트임 하이라이트'], def: '코 쪽 눈 안쪽 끝에 밝은 펄을 콕 찍어 빛나게 한 표현이에요.' },
          { ko: '섀도 없음', en: 'bare eyelids with almost no eyeshadow', tag: '', def: '눈두덩에 섀도를 거의 바르지 않아 맨 눈꺼풀이 보이는 상태예요.' },
          { ko: '오렌지·테라코타 섀도', en: 'orange terracotta warm eyeshadow', syn: ['오렌지 섀도', '브릭 섀도'], def: '주황이나 벽돌색 계열의 따뜻한 섀도예요.' },
          { ko: '골드·브론즈 섀도', en: 'gold bronze shimmer eyeshadow', syn: ['골드 섀도', '브론즈'], def: '금빛이나 청동빛이 도는 따뜻한 반짝임 섀도예요.' },
          { ko: '실버·그레이 섀도', en: 'silver grey cool eyeshadow', syn: ['실버 섀도', '그레이 섀도'], def: '은빛이나 회색 계열의 차가운 섀도예요.' },
          { ko: '컷크리즈', en: 'cut crease eyeshadow with a sharply defined crease line', syn: ['컷 크리즈', '크리즈 강조'], def: '쌍꺼풀 선을 또렷하게 나눠 눈두덩 윤곽을 강조한 섀도예요.' },
        ],
      },
      {
        key: 'eyeLine', label: '아이라인',
        templates: ['a close-up photo of eyes with {}', 'eye makeup with {}'],
        labels: [
          { ko: '캣아이라인', en: 'a sharp lifted cat-eye winged eyeliner', tag: '고양이아이라인', syn: ['고양이 라인', '윙 라인', '여우 라인'], def: '눈꼬리에서 위로 날렵하게 빼 올려 고양이 눈매를 만든 아이라인이에요.' },
          { ko: '강아지 라인', en: 'soft downturned puppy eyeliner extending down at the outer corner', tag: '강아지아이라인', syn: ['강아지 눈매', '처진 라인'], def: '눈꼬리를 아래로 살짝 내려 그려 순하고 처진 눈매를 만든 아이라인이에요.' },
          { ko: '언더라인', en: 'dark eyeliner drawn along the lower lash line or lower waterline', tag: '언더아이라인', syn: ['점막 아이라인', '위아래 라인'], def: '아래 속눈썹 라인이나 아래 점막을 따라 어둡게 그린 아이라인이에요.' },
          { ko: '스머지 라인', en: 'softly smudged dark eyeliner with blurred messy diffused edges', tag: '스머지아이라인', syn: ['번진 아이라인', '더티 스모키'], def: '어두운 아이라인을 그린 뒤 경계를 문질러 흐릿하게 번지게 한 라인이에요.' },
          { ko: '그래픽 라인', en: 'bold graphic eyeliner with sharp geometric shapes, floating crease lines, double wings or bright colored liner', tag: '그래픽아이라인', syn: ['플로팅 라인', '컬러 라이너'], def: '쌍꺼풀 위에 띄운 선, 이중 날개, 원색 라이너처럼 도형적으로 그린 아이라인이에요.' },
          { ko: '내추럴 라인', en: 'a thin natural eyeliner hugging the upper lash line or no visible eyeliner', tag: '', def: '속눈썹 사이만 가늘게 채우거나 거의 보이지 않게 그린 아이라인이에요.' },
          { ko: '컬러 아이라인', en: 'colored eyeliner in blue, green, white or other bright color', syn: ['컬러 라이너', '화이트 라이너'], def: '검정이 아닌 파랑, 초록, 흰색 같은 색으로 그린 아이라인이에요.' },
          { ko: '인라인', en: 'tightline eyeliner drawn only on the inner waterline', syn: ['점막 라인', '타이트라인'], def: '속눈썹 사이 점막만 채워 티 나지 않게 또렷하게 만든 라인이에요.' },
          { ko: '아이라인 없음', en: 'eye makeup with no visible eyeliner', syn: ['노 라이너', '라인 생략'], def: '아이라인을 그리지 않은 눈 메이크업이에요.' },
        ],
      },
      {
        key: 'lash', label: '속눈썹',
        templates: ['a close-up photo of eyes with {}', 'eye makeup with {}'],
        labels: [
          { ko: '인형 속눈썹', en: 'dramatic long separated doll-like upper lashes', tag: '인형속눈썹', syn: ['가닥 속눈썹', '아이돌 속눈썹'], def: '윗속눈썹을 길고 가닥가닥 갈라지게 올려 인형처럼 보이게 한 속눈썹이에요.' },
          { ko: '언더 속눈썹', en: 'emphasized lower eyelashes, separated spiky bottom lashes clearly visible below the eye', tag: '언더속눈썹', syn: ['언더래쉬', '아랫속눈썹'], def: '아래 속눈썹을 가닥가닥 뾰족하게 살려 눈 아래에 또렷이 보이게 한 표현이에요.' },
          { ko: '컬러 마스카라', en: 'eyelashes coated in non-black colored mascara such as blue, white, green or pink', tag: '컬러마스카라', syn: ['컬러 래시'], def: '파랑, 흰색, 초록, 분홍처럼 검정이 아닌 색 마스카라를 바른 속눈썹이에요.' },
          { ko: '내추럴 속눈썹', en: 'natural curled lashes with simple black mascara', tag: '', def: '가볍게 컬을 올리고 검은 마스카라만 바른 자연스러운 속눈썹이에요.' },
          { ko: '스파이키 속눈썹', en: 'spiky clumped lashes separated into bold spikes', syn: ['뭉친 속눈썹', '클럼피 래쉬'], def: '속눈썹을 몇 가닥씩 뭉쳐 뾰족하게 연출한 모양이에요.' },
          { ko: '속눈썹 생략', en: 'eyes with no mascara or lash makeup', syn: ['노 마스카라', '속눈썹 없음'], def: '마스카라나 속눈썹 연출을 하지 않은 상태예요.' },
        ],
      },
      {
        key: 'brow', label: '눈썹', tagSuffix: '',
        templates: ['a close-up photo of a face with {}', 'makeup with {}'],
        labels: [
          { ko: '일자 눈썹', en: 'straight flat eyebrows with little or no arch', tag: '일자눈썹', syn: ['일자 브로우'], def: '눈썹산이 거의 없이 가로로 곧게 뻗은 눈썹이에요.' },
          { ko: '아치 눈썹', en: 'arched eyebrows with a clear peak and a curved tapered shape', tag: '아치눈썹', syn: ['아치형 눈썹'], def: '눈썹산이 뚜렷하게 솟고 꼬리로 갈수록 가늘게 휘어지는 눈썹이에요.' },
          { ko: '탈색 눈썹', en: 'bleached very light blonde eyebrows that are almost invisible', tag: '탈색눈썹', syn: ['블리치 브로우'], def: '아주 밝게 탈색해 거의 보이지 않을 만큼 흐려진 눈썹이에요.' },
          { ko: '볼드 눈썹', en: 'bold thick full eyebrows', syn: ['진한 눈썹', '두꺼운 눈썹'], def: '굵고 진하게 채워 존재감이 큰 눈썹이에요.' },
          { ko: '얇은 눈썹', en: 'thin skinny pencil-line eyebrows', syn: ['가는 눈썹', '씬 브로우'], def: '가늘게 다듬어 선처럼 얇은 눈썹이에요.' },
          { ko: '브러시업 눈썹', en: 'brushed-up feathered fluffy eyebrows', syn: ['페더 브로우', '결 눈썹'], def: '눈썹 결을 위로 빗어 올려 자연스럽고 풍성해 보이는 눈썹이에요.' },
          { ko: '각진 눈썹', en: 'angular sharply defined eyebrows with a high arch and crisp edges', syn: ['각 눈썹', '샤프 브로우'], def: '산 부분이 높고 선이 또렷하게 각진 눈썹이에요.' },
        ],
      },
      {
        key: 'lip', label: '립 컬러', tagSuffix: '립',
        templates: ['a close-up photo of lips with {}', 'makeup with {}'],
        labels: [
          { ko: '레드', en: 'classic red lipstick', tone: 'neutral', syn: ['체리', '토마토', '브릭 레드'], def: '체리나 토마토처럼 선명한 빨간색 입술이에요.' },
          { ko: '코랄', en: 'coral peach lipstick', tone: 'warm', syn: ['피치', '살구'], def: '주황빛이 섞인 산호색이나 복숭아색 입술이에요.' },
          { ko: '로즈핑크', en: 'rosy pink lipstick', tone: 'cool', syn: ['핑크', '베이비 핑크'], def: '말린장미보다 밝고 맑은 장밋빛 분홍색 입술이에요.' },
          { ko: 'MLBB', en: 'nude natural my-lips-but-better lipstick', tone: 'neutral', syn: ['누드', '내 입술색'], def: '원래 입술색보다 조금 더 생기 있어 보이는 자연스러운 누드 톤 입술이에요.' },
          { ko: '말린장미', en: 'muted dusty rose lipstick', tone: 'cool', syn: ['모브', '번트 로즈'], def: '장미 꽃잎을 말린 듯 회갈색이 섞인 차분한 장밋빛 입술이에요.' },
          { ko: '버건디·플럼', en: 'deep burgundy plum lipstick', tone: 'cool', tag: '버건디립', syn: ['딥 베리', '와인'], def: '와인이나 자두처럼 검붉고 깊은 색 입술이에요.' },
          { ko: '오렌지', en: 'bright orange lipstick', tone: 'warm', syn: ['탠저린', '테라코타'], def: '귤처럼 선명하고 밝은 주황색 입술로, 코랄보다 분홍기가 적어요.' },
          { ko: '브라운', en: '90s brown lipstick', tone: 'warm', syn: ['초코브라운', '모카무스'], def: '1990년대에 유행한 초콜릿이나 모카 같은 갈색 입술이에요.' },
          { ko: '퍼플', en: 'sheer lilac or violet purple lipstick', tone: 'cool', syn: ['라일락 립', '바이올렛 립'], def: '연보라나 바이올렛 같은 보랏빛을 얇게 입힌 입술이에요.' },
          { ko: '블랙', en: 'black or near-black dark gothic lipstick', tone: 'neutral', syn: ['다크 립'], def: '검은색이나 검정에 가까운 아주 어두운 색 입술이에요.' },
          { ko: '핫핑크·푸시아', en: 'hot pink fuchsia lipstick', tone: 'cool', syn: ['푸시아', '비비드 핑크'], def: '아주 선명하고 진한 분홍 입술이에요.' },
          { ko: '누드·베이지', en: 'nude beige lipstick', tone: 'neutral', syn: ['누드립', '베이지립'], def: '피부색에 가까운 연한 베이지 입술이에요.' },
          { ko: '피치', en: 'peach soft orange-pink lipstick', tone: 'warm', syn: ['피치립', '살구색'], def: '살구처럼 부드러운 주황빛 분홍 입술이에요.' },
        ],
      },
      {
        key: 'lipTexture', label: '립 표현',
        templates: ['a close-up photo of {}', 'lips with {}'],
        labels: [
          { ko: '글로시', en: 'shiny glossy wet-look lips', tag: '글로시립', syn: ['물먹립', '탕후루 립', '립 오일'], def: '물을 머금은 듯 반짝이고 촉촉하게 광이 나는 입술이에요.' },
          { ko: '매트', en: 'matte velvet lipstick', tag: '매트립', syn: ['벨벳', '벨벳 틴트'], def: '광 없이 벨벳처럼 보송하고 부드럽게 마무리한 입술이에요.' },
          { ko: '블러립', en: 'soft-focus blurred lips with a diffused powdery edge', syn: ['블러드 립', '립 블러링'], def: '입술 윤곽을 흐릿하게 퍼뜨려 경계가 뿌옇게 번져 보이는 입술이에요.' },
          { ko: '그라데이션립', en: 'korean gradient lips, deeper color in the center fading outward', syn: ['비튼 립', '이너 립'], def: '입술 안쪽은 진하고 바깥으로 갈수록 연해지게 물들인 입술이에요.' },
          { ko: '오버립', en: 'overlined full lips drawn slightly beyond the natural lip line', syn: ['오버라인'], def: '원래 입술선보다 살짝 바깥으로 그려 도톰하게 보이게 한 입술이에요.' },
          { ko: '립라인 강조', en: 'lips outlined with a visibly darker lip liner blended into a lighter or glossy center, a defined 90s lip contour', tag: '립라이너메이크업', syn: ['90년대 립', '헤일로 립', '립 스컬프팅'], def: '입술 테두리를 더 진한 라이너로 그리고 안쪽은 밝게 채운 90년대식 입술이에요.' },
          { ko: '프로스티드 립', en: 'frosted pearly shimmering lips in icy pale pink or nude', tag: '펄립', syn: ['펄 립', '프로스트 립'], def: '연분홍이나 누드 톤에 서리 같은 펄이 반짝이는 입술이에요.' },
          { ko: '쉬어 틴트', en: 'sheer tint lips with light see-through color', syn: ['틴트', '물들인 입술'], def: '색이 비치듯 얇게 물든 가벼운 입술 표현이에요.' },
          { ko: '새틴', en: 'satin finish lips, soft sheen between matte and glossy', syn: ['세미 글로시', '새틴 립'], def: '매트와 글로시 사이의 은은한 광이 도는 입술 표현이에요.' },
        ],
      },
      {
        key: 'cheek', label: '치크·윤곽',
        templates: ['a photo of a face with {}', 'makeup featuring {}'],
        labels: [
          { ko: '홍조 블러셔', en: 'pink-red blush spread across both cheeks and connected over the nose bridge, a sun-kissed flushed look', syn: ['콧등 블러셔', '선번'], def: '양 볼과 콧등까지 이어지게 붉은 블러셔를 펴 발라 햇볕에 달아오른 듯한 표현이에요.' },
          { ko: '숙취 블러셔', en: 'blush placed high directly under the eyes on the upper cheekbones, a flushed tipsy look', tag: '숙취메이크업', syn: ['이가리 메이크업', '눈밑 블러셔'], def: '눈 바로 아래 광대 윗부분에 블러셔를 올려 술기운이 오른 듯 보이게 한 표현이에요.' },
          { ko: '코랄 블러셔', en: 'warm coral peach blush on the cheeks', syn: ['피치 블러셔', '복숭아 블러셔'], def: '볼에 주황빛 도는 코랄이나 복숭아색 블러셔를 바른 표현이에요.' },
          { ko: '베리 블러셔', en: 'deep berry or plum-toned blush on the cheeks', syn: ['플럼 블러셔'], def: '볼에 산딸기나 자두처럼 진한 베리색 블러셔를 바른 표현이에요.' },
          { ko: '셰이딩', en: 'sculpted contoured cheekbones and jawline', syn: ['컨투어', '윤곽 메이크업'], def: '광대 아래와 턱선에 어두운 색을 넣어 얼굴 윤곽을 깎은 듯 보이게 한 표현이에요.' },
          { ko: '하이라이터', en: 'glowing highlighter on the cheekbones and nose bridge', syn: ['스트로빙'], def: '광대 위와 콧대에 밝은 펄을 발라 빛이 맺혀 보이게 한 표현이에요.' },
          { ko: '미니멀', en: 'almost no blush or contour', tag: '', def: '블러셔나 셰이딩을 거의 쓰지 않아 볼이 맨얼굴에 가까운 상태예요.' },
          { ko: '피치 블러셔', en: 'peach orange blush on the cheeks', syn: ['오렌지 블러셔', '피치 치크'], def: '살구나 주황빛 블러셔예요.' },
          { ko: '드레이핑 블러셔', en: 'draping blush swept widely from the cheeks up to the temples', syn: ['드레이핑', '넓은 블러셔'], def: '볼에서 관자놀이까지 넓게 쓸어 올린 블러셔예요.' },
          { ko: '브론저', en: 'bronzer warm sun-kissed glow on the cheeks and forehead', syn: ['브론징', '선탠 메이크업'], def: '햇볕에 그을린 듯 따뜻한 갈색을 볼과 이마에 올린 표현이에요.' },
        ],
      },
      {
        key: 'detail', label: '포인트',
        templates: ['a close-up photo of a face with {}', 'makeup with {}'],
        labels: [
          { ko: '큐빅·파츠', en: 'small rhinestones, crystals, pearls or star stickers glued on the face around the eyes or on the nose bridge', tag: '큐빅메이크업', syn: ['파츠 메이크업', '페이스 젬', '눈물 큐빅'], def: '눈가나 콧등에 작은 큐빅, 진주, 별 스티커를 붙여 꾸민 메이크업이에요.' },
          { ko: '주근깨', en: 'small drawn-on freckles scattered across the nose bridge and upper cheeks', tag: '주근깨메이크업', syn: ['프레클', '선번 메이크업'], def: '콧등과 볼 윗부분에 작은 점을 흩뿌리듯 그려 넣은 표현이에요.' },
          { ko: '포인트 없음', en: 'clean skin with no face gems, stickers or freckles', tag: '', hidden: true, def: '얼굴에 큐빅, 스티커, 그려 넣은 주근깨 같은 장식이 없는 상태예요.' },
          { ko: '페이스 페인팅', en: 'face painting or decorative painted lines and shapes on the face', syn: ['페이스 아트', '그래픽 페인팅'], def: '얼굴에 선이나 무늬를 그려 넣은 장식이에요.' },
          { ko: '페이크 점', en: 'fake beauty mark or drawn mole on the face', syn: ['애교점', '뷰티 마크'], def: '점을 그려 넣어 포인트를 준 장식이에요.' },
        ],
      },
      {
        key: 'tone', label: '톤', tagSuffix: '메이크업',
        templates: ['a photo of {}', '{}'],
        labels: [
          { ko: '쿨톤', en: 'cool-toned makeup with pink, rose, berry, plum or silver colors', syn: ['여름쿨', '겨울쿨'], def: '분홍, 로즈, 베리, 자두색, 은색처럼 푸른 기가 도는 색 위주의 메이크업이에요.' },
          { ko: '웜톤', en: 'warm-toned makeup with coral, peach, orange, gold or brown colors', syn: ['봄웜', '가을웜'], def: '코랄, 복숭아, 주황, 금색, 갈색처럼 노란 기가 도는 색 위주의 메이크업이에요.' },
          { ko: '뉴트럴', en: 'neutral-toned makeup with balanced natural colors', tag: '', syn: ['미지근톤'], def: '푸른 기나 노란 기 어느 쪽으로도 치우치지 않은 중간 색 위주의 메이크업이에요.' },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────── 타투
  tattoo: {
    label: '타투',
    icon: '🖋️',
    detect: [
      'a photo of a tattoo on skin',
      'a close-up photo of tattooed skin',
      'a photo of a person showing their tattoo',
    ],
    groups: [
      {
        key: 'style', label: '장르', tagSuffix: '타투',
        templates: ['a photo of a {} tattoo', 'a {} style tattoo on skin'],
        labels: [
          { ko: '레터링', en: 'lettering script calligraphy text', syn: ['문구 타투'], def: '글자나 문장을 필기체, 캘리그래피 같은 서체로 새긴 타투예요.' },
          { ko: '파인라인', en: 'fine line single-needle delicate thin-line', syn: ['라인워크', '감성타투', 'K타투'], def: '바늘 하나로 머리카락처럼 가는 선만 써서 섬세하게 그린 타투예요.' },
          { ko: '미니멀', en: 'tiny minimalist simple symbol', syn: ['심플타투', '심볼타투'], def: '단순한 선과 도형으로 작은 기호나 모양을 간결하게 그린 타투예요.' },
          { ko: '두들', en: 'doodle with wobbly thin lines and childlike simple scribble drawings', syn: ['낙서타투', '이그노런트'], def: '펜으로 낙서한 듯 삐뚤빼뚤한 가는 선과 아이 그림 같은 단순한 도안의 타투예요.' },
          { ko: '블랙워크', en: 'bold solid black ink blackwork with flat black fills and no grey shading', def: '회색 음영 없이 검은 잉크로 굵게 면을 채우고 무늬를 그린 타투예요.' },
          { ko: '블랙아웃', en: 'blackout, a large area of skin completely filled with solid black ink', syn: ['블랙암'], def: '피부의 넓은 부분을 빈틈없이 검은 잉크로 가득 채운 타투예요.' },
          { ko: '블랙앤그레이', en: 'black and grey with soft smooth grey wash shading', def: '검은 잉크를 묽게 풀어 만든 부드러운 회색 음영으로 표현한 흑백 타투예요.' },
          { ko: '리얼리즘', en: 'photorealistic realism that looks like a photograph with lifelike lighting and depth', syn: ['리얼리스틱', '포트레이트'], def: '빛과 입체감까지 살려 사진처럼 실제와 똑같이 그린 타투예요.' },
          { ko: '치카노', en: 'chicano black and grey with soft smoky shading, cursive script, rosaries and clown masks', syn: ['촐로'], def: '멕시코계 미국인 문화에서 나온 흑백 음영 타투로, 필기체 글씨, 묵주, 광대 가면이 자주 나와요.' },
          { ko: '올드스쿨', en: 'american traditional old school with bold outlines and red, yellow and green colors', syn: ['아메리칸 트래디셔널', '트래디셔널'], def: '굵은 검은 윤곽선과 빨강·노랑·초록 같은 원색으로 칠한 미국 전통 도안이에요.' },
          { ko: '네오트래디셔널', en: 'neo traditional with bold outlines, rich colors and ornate detail', def: '올드스쿨에서 발전한 장르로, 굵은 윤곽선에 더 풍부한 색과 섬세한 장식을 더해요.' },
          { ko: '뉴스쿨', en: 'new school cartoon-like exaggerated colorful', syn: ['팝아트 타투', '카툰'], def: '만화처럼 형태를 과장하고 밝고 강한 색을 가득 쓴 타투예요.' },
          { ko: '애니', en: 'anime manga character with clean even outlines and flat cel-shaded colors', syn: ['애니타투', '만화 타투'], def: '일본 애니메이션·만화 캐릭터를 고른 윤곽선과 평평한 색칠로 그린 타투예요.' },
          { ko: '이레즈미', en: 'japanese irezumi with waves, koi, peonies, dragons or hannya masks', syn: ['재패니즈', '뉴재패니즈'], def: '파도, 잉어, 모란, 용, 귀신 가면 같은 소재를 굵은 선으로 그린 일본 전통 타투예요.' },
          { ko: '동양화', en: 'east asian ink-wash painting style with loose black brush strokes and soft grey ink gradients', syn: ['수묵화타투', '붓터치타투', '오리엔탈'], def: '먹으로 그린 수묵화처럼 붓 자국과 번지는 회색 농담을 살린 타투예요.' },
          { ko: '수채화', en: 'watercolor with soft color washes and bleeding splashes, often without outlines', def: '윤곽선을 생략하거나 줄이고 물감이 번지고 튄 듯한 색으로 표현한 타투예요.' },
          { ko: '일러스트', en: 'illustrative sketch-like drawing', syn: ['스케치 타투'], def: '연필 스케치나 펜 드로잉처럼 그림체가 살아 있는 타투예요.' },
          { ko: '도트워크', en: 'dotwork with shading made entirely of tiny stippled dots', def: '작은 점을 수없이 찍어 명암과 형태를 만든 타투예요.' },
          { ko: '지오메트릭', en: 'geometric with precise straight lines, triangles, circles and symmetrical sacred geometry', syn: ['기하학타투'], def: '곧은 선, 삼각형, 원을 정확하게 대칭으로 배치한 기하학 무늬 타투예요.' },
          { ko: '오너멘탈', en: 'ornamental with symmetrical decorative filigree, lace and jewelry-like patterns', syn: ['장식 타투', '레이스 타투'], def: '레이스나 장신구처럼 좌우 대칭으로 섬세하게 장식한 무늬 타투예요.' },
          { ko: '트라이벌', en: 'tribal polynesian black pattern', syn: ['폴리네시안', '마오리'], def: '폴리네시아·마오리 원주민 문양에서 온 굵은 검은 곡선 무늬 타투예요.' },
          { ko: '네오트라이벌', en: 'neo-tribal with bold solid black flowing shapes ending in sharp thorn-like spikes', syn: ['Y2K 트라이벌'], def: '트라이벌을 변형해 검게 채운 굵은 곡선이 가시처럼 뾰족하게 끝나는 2000년대풍 타투예요.' },
          { ko: '사이버시길리즘', en: 'cybersigilism with sharp thin spiky flowing black lines like chrome thorns', syn: ['시길리즘'], def: '2020년대에 퍼진 장르로, 금속 가시처럼 가늘고 날카로운 검은 선이 흐르듯 뻗어요.' },
          { ko: '트래쉬폴카', en: 'trash polka collage with black realistic images and bold red ink splatters', def: '독일에서 시작된 장르로, 검은 사실적 이미지와 굵은 빨간 잉크 얼룩을 콜라주처럼 섞어요.' },
          { ko: '핸드포크', en: 'hand-poked stick and poke tattoo with dotted hand-made lines', syn: ['스틱앤포크', '손타투'], def: '기계 없이 바늘로 한 점씩 찍어 만든 소박한 타투예요.' },
          { ko: '바이오메카닉', en: 'biomechanical tattoo showing machinery and robot parts under torn skin', syn: ['바이오메카', '메카닉'], def: '피부 아래 기계 장치가 드러난 것처럼 그린 타투예요.' },
          { ko: '스케치', en: 'sketch style tattoo with rough pencil-like lines and unfinished strokes', syn: ['스케치 타투', '드로잉 스타일'], def: '연필 스케치처럼 거칠고 미완성 같은 선으로 그린 타투예요.' },
        ],
      },
      {
        key: 'color', label: '컬러', tagSuffix: '타투',
        templates: ['a photo of a {} tattoo', 'a {} tattoo on skin'],
        labels: [
          { ko: '블랙', en: 'solid black ink only line', def: '회색 음영 없이 검은 잉크만으로 선이나 면을 그린 타투예요.' },
          { ko: '블랙앤그레이', en: 'black and grey shaded monochrome', def: '색 없이 검정과 여러 단계의 회색 음영으로만 표현한 타투예요.' },
          { ko: '풀컬러', en: 'fully colored vibrant', syn: ['컬러타투'], def: '도안 전체를 여러 가지 선명한 색으로 채운 타투예요.' },
          { ko: '포인트컬러', en: 'mostly black with a small accent of color', def: '대부분 검은 잉크로 그리고 일부에만 색을 살짝 넣은 타투예요.' },
          { ko: '레드', en: 'red ink only', tag: '레드잉크타투', syn: ['레드잉크'], def: '검은 잉크 없이 빨간 잉크만으로 그린 타투예요.' },
          { ko: '파스텔', en: 'soft pale pastel colored', syn: ['소프트컬러'], def: '연분홍, 연보라, 하늘색처럼 연하고 부드러운 색으로 채운 타투예요.' },
          { ko: '화이트 잉크', en: 'white ink tattoo that looks like a faint scar-like design', syn: ['화이트 타투', '흰색 잉크'], def: '흰 잉크로 새겨 피부 위에 은은하게 보이는 타투예요.' },
        ],
      },
      {
        key: 'subject', label: '도안',
        templates: ['a photo of a tattoo of {}', 'a {} tattoo'],
        labels: [
          { ko: '꽃·식물', en: 'flowers, leaves or plants', tag: '꽃타투', syn: ['탄생화', '장미'], def: '장미, 탄생화, 잎사귀처럼 꽃과 식물을 그린 도안이에요.' },
          { ko: '동물', en: 'a wild animal such as a lion, wolf, deer or bear', tag: '동물타투', def: '사자, 늑대, 사슴, 곰 같은 야생동물을 그린 도안이에요.' },
          { ko: '반려동물', en: 'a pet dog or cat portrait', tag: '반려동물타투', syn: ['펫타투'], def: '집에서 기르는 강아지나 고양이의 얼굴을 그린 도안이에요.' },
          { ko: '뱀', en: 'a snake', tag: '뱀타투', def: '몸을 구불구불 휘감거나 길게 뻗은 뱀을 그린 도안이에요.' },
          { ko: '나비·새', en: 'a butterfly or a bird', tag: '나비타투', def: '날개를 편 나비나 날아가는 새처럼 날개 달린 생물을 그린 도안이에요.' },
          { ko: '문구·이니셜', en: 'words, letters, initials or numbers', tag: '이니셜타투', syn: ['레터링', '날짜'], def: '단어, 문장, 이니셜, 날짜처럼 글자나 숫자로 이루어진 도안이에요.' },
          { ko: '만다라·기하학', en: 'a mandala or geometric shapes and lines', tag: '만다라타투', def: '원을 중심으로 대칭 무늬가 퍼지는 만다라나 도형과 선을 조합한 도안이에요.' },
          { ko: '인물', en: 'a human face or portrait', tag: '인물타투', def: '실제 사람이나 인물화의 얼굴, 초상을 그린 도안이에요.' },
          { ko: '달·별·자연', en: 'the moon, stars, sun, waves or mountains', tag: '달타투', def: '밤하늘의 달과 별, 해, 파도, 산 같은 자연을 그린 도안이에요.' },
          { ko: '용·호랑이·잉어', en: 'an asian dragon, tiger, koi fish, phoenix or hannya mask', tag: '동양화타투', def: '동양 전통 그림에 자주 나오는 용, 호랑이, 잉어, 봉황, 귀신 가면을 그린 도안이에요.' },
          { ko: '해골·다크', en: 'a skull, demon or dark gothic motif', tag: '해골타투', syn: ['슈가스컬'], def: '죽음이나 악마를 떠올리게 하는 해골 같은 어두운 소재의 도안이에요.' },
          { ko: '천사·종교', en: 'an angel, a cross, a rosary or praying hands', tag: '천사타투', syn: ['십자가', '묵주'], def: '십자가, 묵주, 기도하는 손, 천사처럼 종교에서 온 소재를 그린 도안이에요.' },
          { ko: '캐릭터', en: 'a cartoon or anime character', tag: '캐릭터타투', def: '만화나 애니메이션에 나오는 캐릭터를 그린 도안이에요.' },
          { ko: '리본·체인', en: 'a ribbon bow, a chain or small hanging charms', tag: '리본타투', def: '묶은 리본, 사슬, 작은 장식이 달린 키링 같은 소품을 그린 도안이에요.' },
          { ko: '하트·심볼', en: 'a small heart, infinity sign or symbol', tag: '하트타투', def: '작은 하트, 무한대 기호처럼 단순한 상징을 그린 도안이에요.' },
          { ko: '사물', en: 'an object such as a clock, key, anchor, dagger or ship', tag: '', def: '시계, 열쇠, 닻, 단검, 배 같은 물건을 그린 도안이에요.' },
          { ko: '파도·바다', en: 'ocean wave or sea themed tattoo', syn: ['파도', '바다'], def: '파도나 바다를 그린 도안이에요.' },
          { ko: '칼·무기', en: 'dagger, sword or weapon tattoo', syn: ['단검', '검'], def: '단검이나 칼 같은 무기를 그린 도안이에요.' },
          { ko: '시계·열쇠', en: 'clock, pocket watch or key tattoo', syn: ['시계', '열쇠'], def: '시계나 열쇠를 그린 도안이에요.' },
          { ko: '음악·악기', en: 'music note or instrument tattoo', syn: ['음표', '악기'], def: '음표나 악기를 그린 도안이에요.' },
          { ko: '풍경·건물', en: 'landscape, mountain scenery or building tattoo', syn: ['풍경', '산'], def: '산이나 풍경, 건물을 그린 도안이에요.' },
        ],
      },
      {
        key: 'placement', label: '부위', tagSuffix: '타투',
        templates: ['a photo of a tattoo on the {}', 'a {} tattoo'],
        labels: [
          { ko: '손목', en: 'wrist', def: '손과 팔뚝이 이어지는 가느다란 관절 부위예요.' },
          { ko: '손·손가락', en: 'hand or fingers', tag: '손가락타투', def: '손등이나 손가락 마디, 손가락 옆면 같은 손 부위예요.' },
          { ko: '팔안쪽', en: 'inner forearm', def: '손목과 팔꿈치 사이에서 손바닥 쪽을 향한 팔 안쪽 면이에요.' },
          { ko: '팔뚝', en: 'outer forearm', def: '손목과 팔꿈치 사이에서 손등 쪽을 향한 팔 바깥 면이에요.' },
          { ko: '어깨·위팔', en: 'upper arm and shoulder', tag: '어깨타투', def: '팔꿈치 위에서 어깨까지 이어지는 윗팔 부위예요.' },
          { ko: '쇄골', en: 'collarbone', def: '목 아래 양쪽으로 가로로 도드라진 뼈 부위예요.' },
          { ko: '가슴', en: 'upper chest', def: '쇄골 아래 가슴 윗부분으로, 도안을 넓게 넣을 수 있는 부위예요.' },
          { ko: '흉골', en: 'sternum between and just below the breasts', syn: ['언더붑'], def: '양쪽 가슴 사이에서 그 바로 아래까지 이어지는 몸 앞 가운데 부위예요.' },
          { ko: '날개뼈', en: 'upper back over the shoulder blade', def: '등 위쪽 양옆에 날개처럼 도드라진 어깨뼈 부위예요.' },
          { ko: '척추', en: 'spine running down the center of the back', def: '목 아래부터 등 한가운데를 따라 세로로 내려가는 등뼈 라인이에요.' },
          { ko: '등', en: 'middle back, a large area of the back', def: '날개뼈 아래부터 허리 위까지 등 가운데의 넓은 부위예요.' },
          { ko: '허리·골반', en: 'lower back or hip bone', tag: '허리타투', def: '엉덩이 바로 위 뒷허리나 앞쪽 골반뼈 주변 부위예요.' },
          { ko: '옆구리', en: 'ribs or side of the torso', def: '겨드랑이 아래부터 허리 위까지, 갈비뼈가 있는 몸통 옆면이에요.' },
          { ko: '허벅지', en: 'thigh', def: '골반 아래부터 무릎 위까지 이어지는 다리 윗부분의 넓은 면이에요.' },
          { ko: '종아리', en: 'calf or shin of the lower leg', def: '무릎과 발목 사이 다리 뒤쪽 근육이나 앞쪽 정강이 부위예요.' },
          { ko: '발목·발등', en: 'ankle or top of the foot', tag: '발목타투', def: '복숭아뼈 주변이나 발가락 위쪽 발 윗면 부위예요.' },
          { ko: '목·귀뒤', en: 'neck or behind the ear', tag: '귀뒤타투', def: '귀 뒤쪽이나 목 옆·뒤처럼 머리카락 가까이 있는 부위예요.' },
          { ko: '배·복부', en: 'tattoo on the stomach or belly', syn: ['배', '복부'], def: '배와 복부에 새긴 타투예요.' },
          { ko: '얼굴·두피', en: 'tattoo on the face or scalp', syn: ['얼굴 타투', '두피'], def: '얼굴이나 머리 두피에 새긴 타투예요.' },
          { ko: '무릎·팔꿈치', en: 'tattoo on the knee or elbow', syn: ['무릎', '팔꿈치'], def: '무릎이나 팔꿈치 관절 부위에 새긴 타투예요.' },
        ],
      },
      {
        key: 'size', label: '크기', tagSuffix: '타투',
        templates: ['a photo of {}', '{} on skin'],
        labels: [
          { ko: '미니', en: 'a tiny tattoo about the size of a fingernail or coin', def: '손톱이나 동전만 한, 대략 1~3cm 크기의 아주 작은 타투예요.' },
          { ko: '스몰', en: 'a small tattoo smaller than a palm', tag: '', def: '손바닥보다 작은 5~7cm 정도 크기의 타투예요.' },
          { ko: '미디엄', en: 'a palm-sized medium tattoo covering part of a limb', tag: '', def: '손바닥만 한 10cm 안팎 크기로 팔다리 일부를 덮는 타투예요.' },
          { ko: '대형', en: 'a large single tattoo bigger than a sheet of paper on the thigh, chest or ribs', def: '허벅지, 가슴, 옆구리 등에 A4 용지보다 크게 하나로 그린 타투예요.' },
          { ko: '반팔', en: 'a half sleeve tattoo covering the whole upper arm from the shoulder to the elbow', tag: '반팔타투', def: '어깨부터 팔꿈치까지 위팔 전체를 덮는 타투예요.' },
          { ko: '긴팔', en: 'a full sleeve tattoo covering the entire arm from the shoulder to the wrist', tag: '긴팔타투', def: '어깨부터 손목까지 팔 전체를 덮는 타투예요.' },
          { ko: '등판', en: 'a back piece tattoo covering most of the back', tag: '등판타투', def: '어깨부터 허리까지 등 대부분을 덮는 큰 타투예요.' },
          { ko: '전신', en: 'a bodysuit tattoo covering the torso, arms and legs', tag: '전신타투', def: '몸통과 팔, 다리까지 이어서 몸 대부분을 덮는 타투예요.' },
        ],
      },
    ],
  },
};

// 그룹별 신뢰도 문구 규칙
// 기준은 보정된 확률(heads/*.json 의 calib)로 잰 실제 적중률에서 정했다 (라벨 폴드 밖 예측 6천여 개)
//   p ≥ 0.9 → 96~97% 맞음 (라벨러끼리의 일치율 수준) · p ≥ 0.5 → 약 83% 맞음
export const CONFIDENCE = {
  high: 0.9,   // 이 이상이면 단정 ("~입니다") — 단정하는 말은 거의 틀리지 않게
  mid: 0.5,    // 이 이상이면 "~로 보입니다" (2위가 가까우면 함께 언급)
};

// 톤 이름 (톤 그룹 결과 → 수식어)
export const TONE_WORDS = {
  쿨톤: { adj: '차가운', short: '쿨' },
  웜톤: { adj: '따뜻한', short: '웜' },
  뉴트럴: { adj: '자연스러운', short: '뉴트럴' },
};
