// 속성 사전 (Taxonomy) — 한국 인스타그램 · 네이버 뷰티 용어 기준
//
// - 각 카테고리는 여러 "속성 그룹"으로 구성되고, 그룹마다 독립적으로 분류한다.
// - ko   : 화면에 보이는 이름 (한국 SNS 에서 실제로 쓰는 표현)
// - en   : 모델(CLIP)에 넣는 영어 설명 — 구체적일수록 정확도가 오른다
// - tag  : 해시태그 (없으면 ko + 그룹의 tagSuffix 로 만든다)
// - tone : 'cool' | 'warm' | 'neutral' — 컬러 라벨이 가진 톤 (톤 판정에 사전 정보로 쓴다)
// - templates : 라벨(en)을 감싸는 문장 틀. 여러 개를 평균내면(prompt ensembling) 안정적이다.
// - hidden    : 화면 후보·태그에 노출하지 않는 보조 라벨
// - syn       : 같은 스타일을 부르는 다른 이름 · 검색어 (화면에 '같은 말'로 보여 주고 검색에 쓴다). 근거는 docs/LABEL_RESEARCH.md

export const CATEGORY_ORDER = ['hair', 'nail', 'makeup', 'tattoo'];

// 뷰티 사진이 아닌 경우를 가려내기 위한 문장 (이쪽이 이기면 "뷰티 사진이 아닐 수 있어요" 안내)
export const OTHER_DETECT = [
  'a photo of a landscape, a street or a building',
  'a photo of food or a drink',
  'a photo of a pet or a wild animal',
  'a product photo of a cosmetic bottle, a tube or a package on a table',
  'a cartoon, a drawing, a painting or an illustration',
  'a photo of hardware, tools, screws or metal nails',
  'a screenshot or a document with text',
  'a photo of a car, furniture or an everyday object',
];

export const TAXONOMY = {
  // ───────────────────────────────────────────────────────────── 헤어
  hair: {
    label: '헤어',
    icon: '💇',
    detect: [
      'a photo of a person showing their hairstyle',
      "a photo of someone's haircut and hair color",
      'a hair salon photo where the hair is the main subject',
    ],
    groups: [
      {
        key: 'length', label: '기장',
        templates: ['a photo of a person with {}', 'a hairstyle photo showing {}'],
        labels: [
          { ko: '숏컷', en: 'very short cropped hair above the ears', syn: ['짧은머리', '남자 짧은머리'] },
          { ko: '단발', en: 'chin-length bob hair that ends around the jawline', syn: ['턱선 단발', '보브 기장'] },
          { ko: '중단발', en: 'medium-length hair that ends at the shoulders or collarbone', syn: ['어깨 기장', '쇄골 기장'] },
          { ko: '긴머리', en: 'long hair that falls well below the shoulders to the chest or back', syn: ['장발', '롱헤어'] },
        ],
      },
      {
        key: 'cut', label: '커트',
        templates: ['a photo of a person with a {}', 'a hairstyle photo of a {}'],
        labels: [
          { ko: '레이어드컷', en: 'layered haircut with soft long layers framing the face', syn: ['버터플라이컷', '롱 레이어드', '레이어드 단발'] },
          { ko: '허쉬컷', en: 'hush cut, a shaggy layered cut with airy wispy textured ends', syn: ['샤기컷', '모던 샤기', '허쉬 숏컷'] },
          { ko: '원랭스', en: 'one-length cut, medium or long hair cut evenly to one straight length with no visible layers', syn: ['원랭스컷', '일자머리'] },
          { ko: '칼단발', en: 'blunt one-length bob cut in a sharp straight horizontal line at the jaw or chin with heavy flat ends and no layers', syn: ['똑단발', '일자단발', '블런트컷'] },
          { ko: '태슬컷', en: 'tassel cut, a near one-length bob or lob whose ends are texturized into soft slightly uneven feathery tips' },
          { ko: '보브컷', en: 'classic rounded bob around the jaw whose ends curve softly under toward the neck in a smooth dome-shaped silhouette', syn: ['프렌치 보브', 'C컬 단발', '슬릭 보브'] },
          { ko: '히메컷', en: 'hime cut, long straight hair with blunt bangs and straight cheek-length side locks', syn: ['공주컷'] },
          { ko: '울프컷', en: 'wolf cut, a choppy shag with short heavy layers on the crown, rough textured ends and a longer thin back' },
          { ko: '멀릿컷', en: 'mullet haircut with short front and sides and noticeably longer hair left at the back of the neck', syn: ['소프트 멀릿', '베이비 멀릿'] },
          { ko: '픽시컷', en: 'pixie cut, a very short cropped feminine haircut' },
          { ko: '빅시컷', en: 'bixie cut, a short shaggy cut between a pixie and a bob with ears partly covered and wispy face-framing layers', syn: ['픽시보브'] },
          { ko: '댄디컷', en: "dandy cut, a neat short men's haircut with a soft fringe covering the forehead", syn: ['시스루댄디', '덮머', '바가지머리'] },
          { ko: '쉼표머리', en: "comma hair, a men's side-parted fringe whose front lock curls inward into a comma shape over the forehead", syn: ['쉼표펌', '콤마헤어'] },
          { ko: '가르마펌', en: "men's side-part perm with a clear side part, the forehead exposed and soft permed volume swept to one side, short sides", syn: ['가르마컷', '2:8 가르마'] },
          { ko: '애즈펌', en: "men's A's perm, a softly permed fringe parted in the middle and curving outward to both sides like curtains, short sides", syn: ['애즈컷', '센터파팅'] },
          { ko: '가일컷', en: "men's short cut where one side of the fringe is swept up off the forehead and the other side falls over the forehead", syn: ['숏가일', '가일펌'] },
          { ko: '리프컷', en: "leaf cut, a men's medium-length cut with long side-parted bangs that sweep outward in a curved leaf shape past the temples" },
          { ko: '아이비리그컷', en: "ivy league cut, a short men's haircut with a neat side part, short tapered sides and a slightly longer top brushed to the side" },
          { ko: '투블럭컷', en: 'two block cut with short shaved sides and longer hair on top', syn: ['언더컷', '투블럭 다운펌'] },
          { ko: '크롭컷', en: "men's textured crop cut, a very short choppy textured top with a short straight fringe across the forehead", syn: ['텍스처드 크롭', '세미크롭', '시저컷'] },
          { ko: '페이드컷', en: "skin fade, a men's haircut whose sides blend gradually from skin-short at the bottom to longer hair on top", syn: ['스킨페이드', '테이퍼 페이드', '바버컷'] },
          { ko: '포마드·슬릭백', en: 'slicked back hair or a pompadour styled with pomade', syn: ['올백', '리젠트'] },
          { ko: '버즈컷', en: 'buzz cut, hair clipped very short all over the head', syn: ['크루컷', '삭발'] },
          { ko: '모히칸', en: 'mohawk with shaved sides and a strip of spiked hair in the middle' },
        ],
      },
      {
        key: 'styling', label: '연출',
        templates: ['a photo of a person with {}', 'a hairstyle with {}'],
        labels: [
          { ko: '풀어내린 머리', en: 'hair worn down loose', tag: '' },
          { ko: '포니테일', en: 'hair tied back in a ponytail', syn: ['하이포니테일', '로우포니테일'] },
          { ko: '똥머리', en: 'hair tied up in a messy loose bun with flyaways on top or at the back of the head', syn: ['메시번'] },
          { ko: '슬릭번', en: 'a sleek bun, hair pulled back tightly and smoothly with no flyaways into a neat compact bun', syn: ['클린번', '로우번', '발레리나 번'] },
          { ko: '반묶음', en: 'half-up half-down hair', syn: ['하프업'] },
          { ko: '양갈래', en: 'pigtails, hair tied into two sections on both sides', syn: ['만두머리', '트윈테일'] },
          { ko: '땋은머리', en: 'braided hair with braids or cornrows', syn: ['디스코머리', '피쉬테일', '콘로우'] },
          { ko: '드레드', en: 'dreadlocks' },
          { ko: '업스타일', en: 'an elegant formal updo for a wedding or event', syn: ['올림머리', '웨딩 업스타일'] },
          { ko: '집게핀 헤어', en: 'hair twisted up at the back of the head and held by a large claw clip', syn: ['집게핀 머리', '집게핀 업스타일'], tag: '집게핀헤어' },
          { ko: '사과머리', en: 'front bangs gathered and tied up into a small sprout on top of the forehead', syn: ['앞머리 묶기', '분수머리'] },
        ],
      },
      {
        key: 'perm', label: '펌·질감', tagSuffix: '',
        templates: ['a photo of a person with {}', 'a close-up photo of {}'],
        labels: [
          { ko: '생머리', en: 'sleek straight hair with no curls or waves', syn: ['매직', '스트레이트'] },
          { ko: 'C컬펌', en: 'straight hair with the ends curling inward in a soft c-curl', syn: ['볼륨매직', '안C컬'] },
          { ko: '바깥C컬', en: 'flipped ends, hair whose ends curl outward away from the face in a flicked-out curve', syn: ['플립컷', '뻗침 단발'] },
          { ko: 'S컬펌', en: 'loose flowing s-shaped waves through the hair', syn: ['웨이브펌', '쉐도우펌', '릴리펌'] },
          { ko: '물결펌', en: 'water-wave perm, uniform tight continuous zigzag ripple waves from near the roots to the ends', syn: ['물결 웨이브', 'SS컬펌'] },
          { ko: '빌드펌', en: 'glamorous big voluminous bouncy curls from the mid-lengths', syn: ['엘리자벳펌', '글램펌'] },
          { ko: '젤리펌', en: 'jelly perm, bouncy springy medium-sized spiral curls with glossy definition, looser than a hippie perm', syn: ['그레이스펌', '탱글펌'] },
          { ko: '히피펌', en: 'hippie perm, small tight voluminous frizzy curls all over', syn: ['베이비펌'] },
          { ko: '내추럴 곱슬', en: 'natural curly or coily afro-textured hair', syn: ['곱슬머리', '아프로'] },
        ],
      },
      {
        key: 'bangs', label: '앞머리',
        templates: ['a photo of a person with {}', 'a hairstyle with {}'],
        labels: [
          { ko: '앞머리 없음', en: 'no bangs, hair swept away from a visible forehead', tag: '', syn: ['깐머리', '이마 노출'] },
          { ko: '풀뱅', en: 'full thick blunt bangs covering the forehead', syn: ['일자 앞머리'] },
          { ko: '처피뱅', en: 'choppy micro bangs, very short blunt bangs cut well above the eyebrows at mid-forehead', syn: ['마이크로뱅', '숏뱅'] },
          { ko: '시스루뱅', en: 'thin wispy see-through bangs', syn: ['위스피뱅', '에어뱅'] },
          { ko: 'U뱅', en: 'u-shaped bangs, a wispy fringe shortest in the center at eyebrow level that grows longer toward the temples in a soft arch', syn: ['U자 앞머리'] },
          { ko: '사이드뱅', en: 'side-swept bangs brushed to one side', syn: ['깻잎머리', '옆 가르마'] },
          { ko: '커튼뱅', en: 'curtain bangs parted in the middle framing the face', syn: ['가운데 가르마'] },
          { ko: '애교머리', en: 'face-framing wisps, a few short loose strands falling along the temples and cheeks while the forehead stays open', syn: ['애교뱅', '잔머리'] },
          { ko: '확인 불가', en: 'the back of the head seen from behind, the forehead is not visible', hidden: true },
        ],
      },
      {
        key: 'color', label: '컬러',
        templates: ['a photo of a person with {}', 'a hair color photo of {}'],
        labels: [
          { ko: '흑발', en: 'natural jet black hair', tone: 'neutral' },
          { ko: '블루블랙', en: 'blue-black hair, black with a cool blue sheen', tone: 'cool', syn: ['미드나잇블루'] },
          { ko: '초코브라운', en: 'rich dark chocolate brown hair', tone: 'warm', syn: ['다크브라운'] },
          { ko: '밀크브라운', en: 'soft light milky beige brown hair', tone: 'neutral', syn: ['밀크티브라운', '모카브라운'] },
          { ko: '애쉬베이지', en: 'ash beige hair, a light muted greyish beige between light brown and blonde, matte and low-saturation', tone: 'cool', syn: ['밀크베이지', '샌드베이지'] },
          { ko: '애쉬브라운', en: 'cool ash brown hair with a greyish muted tone', tone: 'cool' },
          { ko: '카키브라운', en: 'khaki brown hair with an olive greenish tint', tone: 'cool', syn: ['매트브라운', '올리브브라운'] },
          { ko: '골드브라운', en: 'warm golden caramel brown hair', tone: 'warm', syn: ['카라멜브라운', '테디베어 브라운'] },
          { ko: '오렌지브라운', en: 'orange copper brown hair', tone: 'warm', syn: ['코퍼브라운'] },
          { ko: '핑크브라운', en: 'rose brown hair, a soft muted brown with a subtle pinkish rosy tint', tone: 'neutral', syn: ['로즈브라운', '코랄브라운'] },
          { ko: '레드와인', en: 'wine red burgundy hair', tone: 'cool', syn: ['체리브라운', '레드브라운', '버건디'] },
          { ko: '애쉬블론드', en: 'cool ash or platinum blonde hair', tone: 'cool', syn: ['플래티넘', '백금발'] },
          { ko: '골드블론드', en: 'warm golden honey blonde hair', tone: 'warm', syn: ['허니블론드'] },
          { ko: '애쉬그레이', en: 'ash grey or silver hair', tone: 'cool', syn: ['실버', '백발 염색'] },
          { ko: '핑크·라벤더', en: 'pastel pink or lavender dyed hair', tone: 'cool', tag: '핑크염색' },
          { ko: '블루·퍼플', en: 'vivid blue or purple dyed hair', tone: 'cool', tag: '블루염색' },
          { ko: '그린·민트', en: 'green or mint dyed hair', tone: 'cool', tag: '민트염색' },
          { ko: '비비드 레드', en: 'vivid bright red dyed hair', tone: 'warm' },
        ],
      },
      {
        key: 'colorTech', label: '컬러 기법',
        templates: ['a photo of a person with {}', 'a hair color photo of {}'],
        labels: [
          { ko: '전체 염색', en: 'hair in one single even color from root to tip', tag: '' },
          { ko: '브릿지', en: 'one or a few bold chunky streaks of contrasting color, often a bright strand at the front framing the face', syn: ['앞머리 브릿지', '머니피스'] },
          { ko: '하이라이트', en: 'highlights, many fine thin streaks of lighter blonde or caramel color woven evenly through darker hair', syn: ['위빙', '부분탈색'] },
          { ko: '발레아쥬', en: 'balayage, soft hand-painted lighter color through the lengths', syn: ['컬러 멜팅'] },
          { ko: '옴브레', en: 'ombre hair, dark roots gradually fading to a light color at the ends', syn: ['그라데이션 염색'] },
          { ko: '이너컬러', en: 'hidden inner color, a bright color peeking from the underneath layer', syn: ['시크릿투톤', '히든컬러'] },
          { ko: '투톤', en: 'two-tone hair split into two distinct colors', syn: ['반반염색'] },
        ],
      },
      {
        key: 'tone', label: '톤', tagSuffix: '염색',
        templates: ['a photo of a person with {}', '{}'],
        labels: [
          { ko: '쿨톤', en: 'cool-toned hair color with ashy grey, blue or violet undertones and no warmth' },
          { ko: '웜톤', en: 'warm-toned hair color with golden, orange, copper or reddish undertones' },
          { ko: '뉴트럴', en: 'natural neutral-toned hair color, neither warm nor ashy', tag: '' },
        ],
      },
      {
        key: 'mood', label: '분위기', tagSuffix: '헤어',
        templates: ['a photo of a {} hairstyle', 'a {} hair look'],
        labels: [
          { ko: '청순', en: 'innocent pure and soft-looking' },
          { ko: '러블리', en: 'cute lovely and girly' },
          { ko: '시크', en: 'chic cool and sophisticated' },
          { ko: '힙', en: 'hip edgy bold street-style' },
          { ko: '내추럴', en: 'natural effortless and casual', syn: ['꾸안꾸'] },
          { ko: '단정·오피스', en: 'neat tidy and professional', tag: '단정한헤어' },
          { ko: '우아·고급', en: 'elegant glamorous and luxurious', tag: '고급스러운헤어', syn: ['올드머니'] },
          { ko: '레트로', en: 'retro vintage' },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────── 네일
  nail: {
    label: '네일',
    icon: '💅',
    detect: [
      'a close-up photo of fingernails with nail polish',
      'a photo of a manicure with nail art',
      'a photo of a hand showing painted nails',
      'a photo of painted toenails, a pedicure on bare feet',
    ],
    groups: [
      {
        key: 'shape', label: '쉐입', tagSuffix: '쉐입',
        templates: ['a close-up photo of {} nails', 'a manicure with {} nail shape'],
        labels: [
          { ko: '라운드', en: 'short rounded' },
          { ko: '오벌', en: 'oval shaped' },
          { ko: '스퀘어', en: 'square shaped flat-tipped', syn: ['숏스퀘어'] },
          { ko: '라운드스퀘어', en: 'squoval, square with softly rounded corners', syn: ['스퀘어오벌', '스쿼벌'] },
          { ko: '아몬드', en: 'almond shaped tapered' },
          { ko: '코핀', en: 'coffin ballerina shaped, long tapered with a flat squared tip', syn: ['발레리나'] },
          { ko: '스틸레토', en: 'sharp pointed stiletto' },
          { ko: '플레어', en: 'flared duck-shaped, widening outward toward a broad flat tip', syn: ['덕네일'] },
        ],
      },
      {
        key: 'length', label: '길이',
        templates: ['a close-up photo of {}', 'a manicure on {}'],
        labels: [
          { ko: '숏네일', en: 'short nails trimmed at or just above the fingertip', syn: ['짧은 손톱'] },
          { ko: '미디엄', en: 'medium length nails', tag: '' },
          { ko: '롱네일', en: 'long nails extending well past the fingertip, gel or acrylic extensions', syn: ['연장', '젤연장'] },
        ],
      },
      {
        key: 'color', label: '컬러', tagSuffix: '네일',
        templates: ['a close-up photo of {} nails', 'a manicure in {}'],
        labels: [
          { ko: '누드·베이지', en: 'nude beige', tone: 'warm', tag: '누드네일', syn: ['누디', '스킨톤', '밀크티 베이지'] },
          { ko: '밀키화이트', en: 'milky white sheer translucent', tone: 'neutral' },
          { ko: '화이트', en: 'opaque solid pure white', tone: 'neutral', syn: ['퓨어화이트'] },
          { ko: '연핑크', en: 'soft baby pink', tone: 'cool', syn: ['베이비핑크', '밀키핑크'] },
          { ko: '핫핑크', en: 'bright hot pink', tone: 'cool' },
          { ko: '코랄·피치', en: 'warm coral or peach apricot', tone: 'warm', tag: '코랄네일', syn: ['살구', '피치'] },
          { ko: '레드', en: 'classic red', tone: 'neutral' },
          { ko: '버건디', en: 'deep burgundy wine', tone: 'cool', syn: ['와인', '블랙체리'] },
          { ko: '블랙', en: 'black', tone: 'neutral' },
          { ko: '그레이', en: 'soft grey, milky grey or charcoal grey', tone: 'cool', syn: ['밀크그레이', '차콜'] },
          { ko: '실버', en: 'metallic silver', tone: 'cool' },
          { ko: '골드', en: 'metallic gold', tone: 'warm' },
          { ko: '네이비·블루', en: 'navy or royal blue', tone: 'cool', tag: '블루네일', syn: ['코발트', '로열블루'] },
          { ko: '하늘색', en: 'light sky blue', tone: 'cool', syn: ['아이스블루', '베이비블루'] },
          { ko: '민트·그린', en: 'pastel mint, pistachio or fresh bright green', tone: 'cool', tag: '민트네일', syn: ['피스타치오'] },
          { ko: '올리브·카키', en: 'muted olive green or khaki, a dusty dark green', tone: 'warm', tag: '카키네일', syn: ['카키', '세이지'] },
          { ko: '라벤더·퍼플', en: 'lavender or purple', tone: 'cool', tag: '라벤더네일', syn: ['라일락'] },
          { ko: '버터옐로', en: 'soft creamy pastel butter yellow', tone: 'warm', syn: ['파스텔옐로', '레몬옐로'] },
          { ko: '오렌지', en: 'bright orange or burnt terracotta orange', tone: 'warm', syn: ['테라코타', '탠저린'] },
          { ko: '네온', en: 'fluorescent neon highlighter pink, lime or electric blue', tone: 'neutral', syn: ['형광'] },
          { ko: '브라운·모카', en: 'brown mocha', tone: 'warm', tag: '모카네일', syn: ['모카무스', '초콜릿', '카라멜'] },
        ],
      },
      {
        key: 'design', label: '디자인', tagSuffix: '네일',
        templates: ['a close-up photo of {}', 'nail art with {}'],
        labels: [
          { ko: '원컬러', en: 'plain solid one-color nails with no art' },
          { ko: '프렌치', en: 'french tip nails with a contrasting curved line on the tips' },
          { ko: '마이크로프렌치', en: 'micro french nails with an ultra-thin delicate line of color only at the very edge of the tip', syn: ['헤어라인 프렌치', '얇은 프렌치'] },
          { ko: '딥프렌치', en: 'deep french nails where the colored tip is very thick and covers a large part of the nail', syn: ['두꺼운 프렌치'] },
          { ko: '그라데이션', en: 'gradient ombre nails fading between colors', syn: ['옴브레'] },
          { ko: '글리터', en: 'sparkling chunky glitter nails', syn: ['반짝이', '라메'] },
          { ko: '자석', en: 'magnetic cat eye gel nails with a sharp shimmering band or line of light across the nail', syn: ['캣아이', '자석젤', '마그네틱'] },
          { ko: '벨벳', en: 'velvet magnetic nails with a soft diffused all-over shimmer like brushed velvet and no sharp light band', syn: ['벨벳 자석'] },
          { ko: '오로라', en: 'holographic aurora iridescent nails', syn: ['홀로그램', '유니콘 파우더'] },
          { ko: '크롬', en: 'mirror chrome metallic nails', syn: ['미러파우더', '메탈파우더'] },
          { ko: '글레이즈드', en: 'glazed donut nails, a sheer milky base with a pearly chrome sheen', syn: ['진주파우더', '펄 파우더'] },
          { ko: '자개', en: 'iridescent mother-of-pearl shell flakes inlaid on the nails with a pink-green opal shimmer', syn: ['오팔', '나전'] },
          { ko: '시럽', en: 'syrup jelly nails with translucent glossy sheer color', syn: ['젤리', '시어젤리', '맑은네일'] },
          { ko: '워터드롭', en: 'clear glossy 3D water droplets raised on the nail surface like real drops of water', syn: ['물방울네일', '버블네일'] },
          { ko: '마블', en: 'marble pattern nails with swirls', syn: ['대리석', '잉크마블'] },
          { ko: '치크', en: 'blush aura nails with a soft blurred airbrushed glow of color in the center of each nail', syn: ['블러셔네일', '오라네일'] },
          { ko: '파츠', en: 'nails decorated with flat rhinestones, crystals and small studs', syn: ['스톤', '큐빅', '풀스톤'] },
          { ko: '진주', en: 'nails decorated with small pearls' },
          { ko: '3D조형', en: 'sculpted raised 3D gel art such as drips, waves, bubbles, shells or petals in relief', syn: ['3D네일', '입체 젤아트'], tag: '3D네일' },
          { ko: '크롬하츠', en: 'nails decorated with raised silver 3D gothic cross, heart and chain metal charms', syn: ['메탈 파츠', '십자가 파츠'] },
          { ko: '드로잉', en: 'hand-painted nail art with detailed drawings', syn: ['핸드페인팅', '아트워크'] },
          { ko: '캐릭터', en: 'nails with cute cartoon character faces, smiley faces or emoji drawings or charms', syn: ['산리오', '스마일'] },
          { ko: '과일', en: 'nails painted with small fruit motifs such as cherries, strawberries, lemons or watermelon', syn: ['체리네일', '딸기네일'] },
          { ko: '플라워', en: 'floral flower pattern nails', syn: ['꽃', '압화', '데이지'] },
          { ko: '레이스', en: 'nails with a delicate white or black lace pattern of fine floral mesh over a sheer base' },
          { ko: '호피·애니멀', en: 'leopard print nails with brown and black spots, or other animal prints like zebra, cow or snakeskin', tag: '호피네일', syn: ['레오파드', '지브라'] },
          { ko: '체크', en: 'checkered, gingham, tartan plaid or argyle pattern nails', syn: ['깅엄', '타탄', '아가일'] },
          { ko: '니트·트위드', en: 'nails with a raised 3D cable-knit sweater texture or a speckled woven tweed pattern', tag: '니트네일', syn: ['트위드네일', '스웨터네일'] },
          { ko: '스트라이프', en: 'striped nails with repeated parallel bands of contrasting colors', syn: ['줄무늬'] },
          { ko: '하트·리본', en: 'nails with little hearts or ribbon bows', tag: '리본네일' },
          { ko: '별', en: 'nails with small star shapes or twinkling stars', syn: ['스타', '별자리'] },
          { ko: '도트', en: 'polka dot nails', syn: ['땡땡이', '폴카도트'] },
          { ko: '라인아트', en: 'nails with thin minimalist lines, waves or geometric line art', syn: ['실버라인', '물결라인'] },
        ],
      },
      {
        key: 'layout', label: '구성',
        templates: ['a photo of a manicure with {}', '{}'],
        labels: [
          { ko: '동일디자인', en: 'all nails painted with the same identical color and design', tag: '', syn: ['풀코트'] },
          { ko: '원포인트', en: 'plain nails with only one or two accent nails decorated with art', tag: '포인트네일', syn: ['포인트아트'] },
          { ko: '퐁당퐁당', en: 'nails alternating between two or more different solid colors from finger to finger', syn: ['투톤 네일', '컬러 믹스'] },
          { ko: '오마카세', en: 'every nail with a different mismatched design, a mix of patterns, colors and charms', syn: ['믹스매치', '미스매치'] },
        ],
      },
      {
        key: 'finish', label: '마감', tagSuffix: '네일',
        templates: ['a close-up photo of nails with {}', 'a manicure with {}'],
        labels: [
          { ko: '유광', en: 'a glossy shiny finish', tag: '', syn: ['물광', '글로시'] },
          { ko: '매트', en: 'a flat matte finish with no shine', syn: ['무광'] },
          { ko: '메탈릭', en: 'a reflective metallic finish' },
          { ko: '투명·쉬어', en: 'a translucent sheer see-through finish', tag: '투명네일' },
          { ko: '펄·쉬머', en: 'a pearly shimmery finish', tag: '펄네일', syn: ['진주광', '미세펄'] },
        ],
      },
      {
        key: 'mood', label: '분위기', tagSuffix: '네일',
        templates: ['a photo of {} nails', 'a {} manicure'],
        labels: [
          { ko: '오피스', en: 'simple minimal clean everyday office', syn: ['데일리', '하객네일'] },
          { ko: '청순·러블리', en: 'cute lovely girly soft', tag: '러블리네일' },
          { ko: '화려한', en: 'glamorous elaborate bling', syn: ['블링', '풀파츠'] },
          { ko: '시크·힙', en: 'chic dark edgy', tag: '시크네일', syn: ['고딕', '걸크러시'] },
          { ko: '쇠맛', en: 'cold futuristic silver chrome metallic cyber', syn: ['메탈', '에스파 네일'] },
          { ko: '키치', en: 'playful kitsch y2k with candy colors, cute 3D charms, cherries, hearts and cartoon motifs', syn: ['Y2K', '팝'] },
          { ko: '여름', en: 'fresh summer with clear jelly, ice blue, coral or neon colors, water drops, fruit or ocean motifs', tag: '여름네일', syn: ['바캉스네일', '청량네일'] },
          { ko: '겨울·홀리데이', en: 'cozy winter holiday christmas with red, green, gold glitter, snowflakes or knit textures', tag: '크리스마스네일', syn: ['겨울네일', '연말네일'] },
          { ko: '웨딩', en: 'elegant bridal wedding', syn: ['본식', '브라이덜'] },
        ],
      },
      {
        key: 'part', label: '부위',
        templates: ['a photo of {}', 'a close-up photo of {}'],
        labels: [
          { ko: '핸드', en: 'painted fingernails on a hand', tag: '', syn: ['손톱', '매니큐어'] },
          { ko: '패디', en: 'painted toenails on bare feet, a pedicure', syn: ['패디큐어', '페디', '발톱네일'] },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────── 메이크업
  makeup: {
    label: '메이크업',
    icon: '💄',
    detect: [
      'a close-up photo of a face wearing makeup',
      'a beauty photo showing eye makeup and lipstick',
      'a portrait photo focusing on the makeup look',
    ],
    groups: [
      {
        key: 'mood', label: '무드', tagSuffix: '메이크업',
        templates: ['a photo of a face with {} makeup', 'a {} makeup look'],
        labels: [
          { ko: '데일리', en: 'natural minimal everyday no-makeup style', syn: ['클린걸', '꾸안꾸', '투명 메이크업'] },
          { ko: '청순', en: 'soft innocent fresh pink-toned', syn: ['수채화 메이크업', '첫사랑 메이크업'] },
          { ko: '음영', en: 'soft muted brown contour shading that sculpts the eyes and face', syn: ['모카무스 메이크업', '구운 복숭아'] },
          { ko: '과즙', en: 'fresh juicy fruity makeup with rosy flushed cheeks and glossy tinted lips', syn: ['러블리', '딸기 메이크업'] },
          { ko: '글램', en: 'glamorous full-coverage evening', syn: ['풀메이크업', '파티 메이크업'] },
          { ko: '스모키', en: 'dark dramatic smokey eye' },
          { ko: '걸크러시', en: 'fierce confident edgy makeup with sharp winged eyeliner, defined brows, sculpted contour and strong lips', syn: ['센 언니 메이크업', '시크 메이크업'] },
          { ko: '쇠맛', en: 'cold metallic futuristic cyber makeup with silver chrome shimmer and sharp lines', syn: ['메탈릭 메이크업', 'Y3K'] },
          { ko: 'Y2K', en: 'early-2000s y2k makeup with frosty pastel or icy blue shimmer eyeshadow, frosted pale pink lips and glitter', syn: ['펄 걸 글램', '2000년대 메이크업'] },
          { ko: '갸루', en: 'japanese gyaru makeup with heavy black eyeliner, thick upper and lower lashes, enlarged round eyes and pale glossy lips', syn: ['데일리 갸루'] },
          { ko: '고딕·뱀파이어', en: 'dark gothic vampire makeup with pale matte skin, shadowy smoky eyes and deep wine, plum or black lips', tag: '뱀파이어메이크업', syn: ['흑화 메이크업'] },
          { ko: '레트로', en: 'retro classic pin-up makeup with red or brown defined lips, winged liner and matte skin', syn: ['핀업', '90년대 메이크업'] },
          { ko: '웨딩', en: 'bridal wedding', syn: ['신부화장', '본식 메이크업'] },
          { ko: '아트', en: 'bold artistic colorful stage, festival or face painting', syn: ['무대 메이크업', '페스티벌 메이크업'] },
          { ko: '할로윈·특수분장', en: 'halloween special-effects makeup with fake blood, wounds, scars, stitches, skull or zombie face paint', tag: '할로윈메이크업', syn: ['특수분장', '좀비 메이크업'] },
          { ko: '남자 메이크업', en: "subtle men's grooming makeup on a man, with an even smooth complexion, groomed brows and soft brown shading", tag: '남자메이크업', syn: ['남돌 메이크업', '그루밍 메이크업'] },
        ],
      },
      {
        key: 'base', label: '피부 표현', tagSuffix: '피부',
        templates: ['a close-up photo of a face with {}', 'makeup with {}'],
        labels: [
          { ko: '물광', en: 'very dewy wet-look glass skin', syn: ['물먹광', '유리알 피부', '글래스 스킨'] },
          { ko: '윤광', en: 'soft satin healthy glow from within', syn: ['결광', '속광', '새틴'] },
          { ko: '세미매트', en: 'natural semi-matte skin', syn: ['블러 피부', '소프트 매트'] },
          { ko: '보송 매트', en: 'flat powdery matte skin with no shine', syn: ['매트 피부', '클라우드 스킨'] },
        ],
      },
      {
        key: 'eye', label: '아이섀도',
        templates: ['a close-up photo of eyes with {}', 'eye makeup with {}'],
        labels: [
          { ko: '음영 섀도', en: 'subtle muted brown, mauve or grey shading eyeshadow', tag: '음영섀도', syn: ['브라운 음영', '모브 음영'] },
          { ko: '스모키', en: 'dark smudged smokey eyeshadow around the whole eye in black, grey, plum or brown', syn: ['펄 스모키', '쿨 스모키'] },
          { ko: '글리터·펄', en: 'sparkly glitter shimmer eyeshadow', tag: '글리터섀도', syn: ['눈물 메이크업', '펄 섀도'] },
          { ko: '핑크·코랄 섀도', en: 'pink, coral, peach or orange toned eyeshadow', tag: '코랄섀도', syn: ['피치 섀도', '오렌지 섀도'] },
          { ko: '레드 섀도', en: 'red, brick-red or burgundy eyeshadow, a warm reddish flushed eye area', tag: '레드섀도', syn: ['붉은 섀도', '버건디 섀도'] },
          { ko: '블루 섀도', en: 'blue eyeshadow, icy pale blue, sky blue or cobalt', tag: '블루섀도', syn: ['아이시 블루'] },
          { ko: '퍼플 섀도', en: 'purple, lavender or lilac eyeshadow', tag: '퍼플섀도', syn: ['라벤더 섀도', '연보라 섀도'] },
          { ko: '그린·옐로 섀도', en: 'bright green, lime, mint or lemon-yellow eyeshadow', tag: '그린섀도', syn: ['라임 섀도', '연두 섀도'] },
          { ko: '컬러 섀도', en: 'two or more different bright eyeshadow colors combined on the same eye', syn: ['멀티 컬러 섀도', '무지개 메이크업'] },
          { ko: '애교살 강조', en: 'highlighted aegyo-sal, a shimmery puffy under-eye area', tag: '애교살메이크업' },
          { ko: '눈앞머리 하이라이트', en: 'a bright shimmering highlight spot on the inner corners of the eyes', tag: '눈앞머리하이라이터', syn: ['앞트임 하이라이트'] },
          { ko: '섀도 없음', en: 'bare eyelids with almost no eyeshadow', tag: '' },
        ],
      },
      {
        key: 'eyeLine', label: '아이라인',
        templates: ['a close-up photo of eyes with {}', 'eye makeup with {}'],
        labels: [
          { ko: '캣아이라인', en: 'a sharp lifted cat-eye winged eyeliner', tag: '고양이아이라인', syn: ['고양이 라인', '윙 라인', '여우 라인'] },
          { ko: '강아지 라인', en: 'soft downturned puppy eyeliner extending down at the outer corner', tag: '강아지아이라인', syn: ['강아지 눈매', '처진 라인'] },
          { ko: '언더라인', en: 'dark eyeliner drawn along the lower lash line or lower waterline', tag: '언더아이라인', syn: ['점막 아이라인', '위아래 라인'] },
          { ko: '스머지 라인', en: 'softly smudged dark eyeliner with blurred messy diffused edges', tag: '스머지아이라인', syn: ['번진 아이라인', '더티 스모키'] },
          { ko: '그래픽 라인', en: 'bold graphic eyeliner with sharp geometric shapes, floating crease lines, double wings or bright colored liner', tag: '그래픽아이라인', syn: ['플로팅 라인', '컬러 라이너'] },
          { ko: '내추럴 라인', en: 'a thin natural eyeliner hugging the upper lash line or no visible eyeliner', tag: '' },
        ],
      },
      {
        key: 'lash', label: '속눈썹',
        templates: ['a close-up photo of eyes with {}', 'eye makeup with {}'],
        labels: [
          { ko: '인형 속눈썹', en: 'dramatic long separated doll-like upper lashes', tag: '인형속눈썹', syn: ['가닥 속눈썹', '아이돌 속눈썹'] },
          { ko: '언더 속눈썹', en: 'emphasized lower eyelashes, separated spiky bottom lashes clearly visible below the eye', tag: '언더속눈썹', syn: ['언더래쉬', '아랫속눈썹'] },
          { ko: '컬러 마스카라', en: 'eyelashes coated in non-black colored mascara such as blue, white, green or pink', tag: '컬러마스카라', syn: ['컬러 래시'] },
          { ko: '내추럴 속눈썹', en: 'natural curled lashes with simple black mascara', tag: '' },
        ],
      },
      {
        key: 'brow', label: '눈썹', tagSuffix: '',
        templates: ['a close-up photo of a face with {}', 'makeup with {}'],
        labels: [
          { ko: '일자 눈썹', en: 'straight flat eyebrows with little or no arch', tag: '일자눈썹', syn: ['일자 브로우'] },
          { ko: '아치 눈썹', en: 'arched eyebrows with a clear peak and a curved tapered shape', tag: '아치눈썹', syn: ['아치형 눈썹'] },
          { ko: '탈색 눈썹', en: 'bleached very light blonde eyebrows that are almost invisible', tag: '탈색눈썹', syn: ['블리치 브로우'] },
        ],
      },
      {
        key: 'lip', label: '립 컬러', tagSuffix: '립',
        templates: ['a close-up photo of lips with {}', 'makeup with {}'],
        labels: [
          { ko: '레드', en: 'classic red lipstick', tone: 'neutral', syn: ['체리', '토마토', '브릭 레드'] },
          { ko: '코랄', en: 'coral peach lipstick', tone: 'warm', syn: ['피치', '살구'] },
          { ko: '로즈핑크', en: 'rosy pink lipstick', tone: 'cool', syn: ['핑크', '베이비 핑크'] },
          { ko: 'MLBB', en: 'nude natural my-lips-but-better lipstick', tone: 'neutral', syn: ['누드', '내 입술색'] },
          { ko: '말린장미', en: 'muted dusty rose lipstick', tone: 'cool', syn: ['모브', '번트 로즈'] },
          { ko: '버건디·플럼', en: 'deep burgundy plum lipstick', tone: 'cool', tag: '버건디립', syn: ['딥 베리', '와인'] },
          { ko: '오렌지', en: 'bright orange lipstick', tone: 'warm', syn: ['탠저린', '테라코타'] },
          { ko: '브라운', en: '90s brown lipstick', tone: 'warm', syn: ['초코브라운', '모카무스'] },
          { ko: '퍼플', en: 'sheer lilac or violet purple lipstick', tone: 'cool', syn: ['라일락 립', '바이올렛 립'] },
          { ko: '블랙', en: 'black or near-black dark gothic lipstick', tone: 'neutral', syn: ['다크 립'] },
        ],
      },
      {
        key: 'lipTexture', label: '립 표현',
        templates: ['a close-up photo of {}', 'lips with {}'],
        labels: [
          { ko: '글로시', en: 'shiny glossy wet-look lips', tag: '글로시립', syn: ['물먹립', '탕후루 립', '립 오일'] },
          { ko: '매트', en: 'matte velvet lipstick', tag: '매트립', syn: ['벨벳', '벨벳 틴트'] },
          { ko: '블러립', en: 'soft-focus blurred lips with a diffused powdery edge', syn: ['블러드 립', '립 블러링'] },
          { ko: '그라데이션립', en: 'korean gradient lips, deeper color in the center fading outward', syn: ['비튼 립', '이너 립'] },
          { ko: '오버립', en: 'overlined full lips drawn slightly beyond the natural lip line', syn: ['오버라인'] },
          { ko: '립라인 강조', en: 'lips outlined with a visibly darker lip liner blended into a lighter or glossy center, a defined 90s lip contour', tag: '립라이너메이크업', syn: ['90년대 립', '헤일로 립', '립 스컬프팅'] },
          { ko: '프로스티드 립', en: 'frosted pearly shimmering lips in icy pale pink or nude', tag: '펄립', syn: ['펄 립', '프로스트 립'] },
        ],
      },
      {
        key: 'cheek', label: '치크·윤곽',
        templates: ['a photo of a face with {}', 'makeup featuring {}'],
        labels: [
          { ko: '홍조 블러셔', en: 'pink-red blush spread across both cheeks and connected over the nose bridge, a sun-kissed flushed look', syn: ['콧등 블러셔', '선번'] },
          { ko: '숙취 블러셔', en: 'blush placed high directly under the eyes on the upper cheekbones, a flushed tipsy look', tag: '숙취메이크업', syn: ['이가리 메이크업', '눈밑 블러셔'] },
          { ko: '코랄 블러셔', en: 'warm coral peach blush on the cheeks', syn: ['피치 블러셔', '복숭아 블러셔'] },
          { ko: '베리 블러셔', en: 'deep berry or plum-toned blush on the cheeks', syn: ['플럼 블러셔'] },
          { ko: '셰이딩', en: 'sculpted contoured cheekbones and jawline', syn: ['컨투어', '윤곽 메이크업'] },
          { ko: '하이라이터', en: 'glowing highlighter on the cheekbones and nose bridge', syn: ['스트로빙'] },
          { ko: '미니멀', en: 'almost no blush or contour', tag: '' },
        ],
      },
      {
        key: 'detail', label: '포인트',
        templates: ['a close-up photo of a face with {}', 'makeup with {}'],
        labels: [
          { ko: '큐빅·파츠', en: 'small rhinestones, crystals, pearls or star stickers glued on the face around the eyes or on the nose bridge', tag: '큐빅메이크업', syn: ['파츠 메이크업', '페이스 젬', '눈물 큐빅'] },
          { ko: '주근깨', en: 'small drawn-on freckles scattered across the nose bridge and upper cheeks', tag: '주근깨메이크업', syn: ['프레클', '선번 메이크업'] },
          { ko: '포인트 없음', en: 'clean skin with no face gems, stickers or freckles', tag: '', hidden: true },
        ],
      },
      {
        key: 'tone', label: '톤', tagSuffix: '메이크업',
        templates: ['a photo of {}', '{}'],
        labels: [
          { ko: '쿨톤', en: 'cool-toned makeup with pink, rose, berry, plum or silver colors', syn: ['여름쿨', '겨울쿨'] },
          { ko: '웜톤', en: 'warm-toned makeup with coral, peach, orange, gold or brown colors', syn: ['봄웜', '가을웜'] },
          { ko: '뉴트럴', en: 'neutral-toned makeup with balanced natural colors', tag: '', syn: ['미지근톤'] },
        ],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────── 타투
  tattoo: {
    label: '타투',
    icon: '🖋️',
    detect: [
      'a photo of a tattoo on skin',
      'a close-up photo of tattooed skin',
      'a photo of a person showing their tattoo',
    ],
    groups: [
      {
        key: 'style', label: '장르', tagSuffix: '타투',
        templates: ['a photo of a {} tattoo', 'a {} style tattoo on skin'],
        labels: [
          { ko: '레터링', en: 'lettering script calligraphy text', syn: ['문구 타투'] },
          { ko: '파인라인', en: 'fine line single-needle delicate thin-line', syn: ['라인워크', '감성타투', 'K타투'] },
          { ko: '미니멀', en: 'tiny minimalist simple symbol', syn: ['심플타투', '심볼타투'] },
          { ko: '두들', en: 'doodle with wobbly thin lines and childlike simple scribble drawings', syn: ['낙서타투', '이그노런트'] },
          { ko: '블랙워크', en: 'bold solid black ink blackwork with flat black fills and no grey shading' },
          { ko: '블랙아웃', en: 'blackout, a large area of skin completely filled with solid black ink', syn: ['블랙암'] },
          { ko: '블랙앤그레이', en: 'black and grey with soft smooth grey wash shading' },
          { ko: '리얼리즘', en: 'photorealistic realism that looks like a photograph with lifelike lighting and depth', syn: ['리얼리스틱', '포트레이트'] },
          { ko: '치카노', en: 'chicano black and grey with soft smoky shading, cursive script, rosaries and clown masks', syn: ['촐로'] },
          { ko: '올드스쿨', en: 'american traditional old school with bold outlines and red, yellow and green colors', syn: ['아메리칸 트래디셔널', '트래디셔널'] },
          { ko: '네오트래디셔널', en: 'neo traditional with bold outlines, rich colors and ornate detail' },
          { ko: '뉴스쿨', en: 'new school cartoon-like exaggerated colorful', syn: ['팝아트 타투', '카툰'] },
          { ko: '애니', en: 'anime manga character with clean even outlines and flat cel-shaded colors', syn: ['애니타투', '만화 타투'] },
          { ko: '이레즈미', en: 'japanese irezumi with waves, koi, peonies, dragons or hannya masks', syn: ['재패니즈', '뉴재패니즈'] },
          { ko: '동양화', en: 'east asian ink-wash painting style with loose black brush strokes and soft grey ink gradients', syn: ['수묵화타투', '붓터치타투', '오리엔탈'] },
          { ko: '수채화', en: 'watercolor with soft color washes and bleeding splashes, often without outlines' },
          { ko: '일러스트', en: 'illustrative sketch-like drawing', syn: ['스케치 타투'] },
          { ko: '도트워크', en: 'dotwork with shading made entirely of tiny stippled dots' },
          { ko: '지오메트릭', en: 'geometric with precise straight lines, triangles, circles and symmetrical sacred geometry', syn: ['기하학타투'] },
          { ko: '오너멘탈', en: 'ornamental with symmetrical decorative filigree, lace and jewelry-like patterns', syn: ['장식 타투', '레이스 타투'] },
          { ko: '트라이벌', en: 'tribal polynesian black pattern', syn: ['폴리네시안', '마오리'] },
          { ko: '네오트라이벌', en: 'neo-tribal with bold solid black flowing shapes ending in sharp thorn-like spikes', syn: ['Y2K 트라이벌'] },
          { ko: '사이버시길리즘', en: 'cybersigilism with sharp thin spiky flowing black lines like chrome thorns', syn: ['시길리즘'] },
          { ko: '트래쉬폴카', en: 'trash polka collage with black realistic images and bold red ink splatters' },
        ],
      },
      {
        key: 'color', label: '컬러', tagSuffix: '타투',
        templates: ['a photo of a {} tattoo', 'a {} tattoo on skin'],
        labels: [
          { ko: '블랙', en: 'solid black ink only line' },
          { ko: '블랙앤그레이', en: 'black and grey shaded monochrome' },
          { ko: '풀컬러', en: 'fully colored vibrant', syn: ['컬러타투'] },
          { ko: '포인트컬러', en: 'mostly black with a small accent of color' },
          { ko: '레드', en: 'red ink only', tag: '레드잉크타투', syn: ['레드잉크'] },
          { ko: '파스텔', en: 'soft pale pastel colored', syn: ['소프트컬러'] },
        ],
      },
      {
        key: 'subject', label: '도안',
        templates: ['a photo of a tattoo of {}', 'a {} tattoo'],
        labels: [
          { ko: '꽃·식물', en: 'flowers, leaves or plants', tag: '꽃타투', syn: ['탄생화', '장미'] },
          { ko: '동물', en: 'a wild animal such as a lion, wolf, deer or bear', tag: '동물타투' },
          { ko: '반려동물', en: 'a pet dog or cat portrait', tag: '반려동물타투', syn: ['펫타투'] },
          { ko: '뱀', en: 'a snake', tag: '뱀타투' },
          { ko: '나비·새', en: 'a butterfly or a bird', tag: '나비타투' },
          { ko: '문구·이니셜', en: 'words, letters, initials or numbers', tag: '이니셜타투', syn: ['레터링', '날짜'] },
          { ko: '만다라·기하학', en: 'a mandala or geometric shapes and lines', tag: '만다라타투' },
          { ko: '인물', en: 'a human face or portrait', tag: '인물타투' },
          { ko: '달·별·자연', en: 'the moon, stars, sun, waves or mountains', tag: '달타투' },
          { ko: '용·호랑이·잉어', en: 'an asian dragon, tiger, koi fish, phoenix or hannya mask', tag: '동양화타투' },
          { ko: '해골·다크', en: 'a skull, demon or dark gothic motif', tag: '해골타투', syn: ['슈가스컬'] },
          { ko: '천사·종교', en: 'an angel, a cross, a rosary or praying hands', tag: '천사타투', syn: ['십자가', '묵주'] },
          { ko: '캐릭터', en: 'a cartoon or anime character', tag: '캐릭터타투' },
          { ko: '리본·체인', en: 'a ribbon bow, a chain or small hanging charms', tag: '리본타투' },
          { ko: '하트·심볼', en: 'a small heart, infinity sign or symbol', tag: '하트타투' },
          { ko: '사물', en: 'an object such as a clock, key, anchor, dagger or ship', tag: '' },
        ],
      },
      {
        key: 'placement', label: '부위', tagSuffix: '타투',
        templates: ['a photo of a tattoo on the {}', 'a {} tattoo'],
        labels: [
          { ko: '손목', en: 'wrist' },
          { ko: '손·손가락', en: 'hand or fingers', tag: '손가락타투' },
          { ko: '팔안쪽', en: 'inner forearm' },
          { ko: '팔뚝', en: 'outer forearm' },
          { ko: '어깨·위팔', en: 'upper arm and shoulder', tag: '어깨타투' },
          { ko: '쇄골', en: 'collarbone' },
          { ko: '가슴', en: 'upper chest' },
          { ko: '흉골', en: 'sternum between and just below the breasts', syn: ['언더붑'] },
          { ko: '날개뼈', en: 'upper back over the shoulder blade' },
          { ko: '척추', en: 'spine running down the center of the back' },
          { ko: '등', en: 'middle back, a large area of the back' },
          { ko: '허리·골반', en: 'lower back or hip bone', tag: '허리타투' },
          { ko: '옆구리', en: 'ribs or side of the torso' },
          { ko: '허벅지', en: 'thigh' },
          { ko: '종아리', en: 'calf or shin of the lower leg' },
          { ko: '발목·발등', en: 'ankle or top of the foot', tag: '발목타투' },
          { ko: '목·귀뒤', en: 'neck or behind the ear', tag: '귀뒤타투' },
        ],
      },
      {
        key: 'size', label: '크기', tagSuffix: '타투',
        templates: ['a photo of {}', '{} on skin'],
        labels: [
          { ko: '미니', en: 'a tiny tattoo about the size of a fingernail or coin' },
          { ko: '스몰', en: 'a small tattoo smaller than a palm', tag: '' },
          { ko: '미디엄', en: 'a palm-sized medium tattoo covering part of a limb', tag: '' },
          { ko: '대형', en: 'a large single tattoo bigger than a sheet of paper on the thigh, chest or ribs' },
          { ko: '반팔', en: 'a half sleeve tattoo covering the whole upper arm from the shoulder to the elbow', tag: '반팔타투' },
          { ko: '긴팔', en: 'a full sleeve tattoo covering the entire arm from the shoulder to the wrist', tag: '긴팔타투' },
          { ko: '등판', en: 'a back piece tattoo covering most of the back', tag: '등판타투' },
          { ko: '전신', en: 'a bodysuit tattoo covering the torso, arms and legs', tag: '전신타투' },
        ],
      },
    ],
  },
};

// 그룹별 신뢰도 문구 규칙
// 기준은 보정된 확률(heads/*.json 의 calib)로 잰 실제 적중률에서 정했다 (라벨 폴드 밖 예측 6천여 개)
//   p ≥ 0.9 → 96~97% 맞음 (라벨러끼리의 일치율 수준) · p ≥ 0.5 → 약 83% 맞음
export const CONFIDENCE = {
  high: 0.9,   // 이 이상이면 단정 ("~입니다") — 단정하는 말은 거의 틀리지 않게
  mid: 0.5,    // 이 이상이면 "~로 보입니다" (2위가 가까우면 함께 언급)
};

// 톤 이름 (톤 그룹 결과 → 수식어)
export const TONE_WORDS = {
  쿨톤: { adj: '차가운', short: '쿨' },
  웜톤: { adj: '따뜻한', short: '웜' },
  뉴트럴: { adj: '자연스러운', short: '뉴트럴' },
};
